default_chain: stride
chains:
  stride:
    key: icq1
    chain-id: STRIDE
    rpc-addr: http://stride1:26657
    grpc-addr: http://stride1:9090
    account-prefix: stride
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 1ustrd
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
  gaia:
    key: icq2
    chain-id: GAIA
    rpc-addr: http://gaia1:26657
    grpc-addr: http://gaia1:9090
    account-prefix: cosmos
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 1uatom
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
