[[chains]]
id = 'OSMO'
rpc_addr = 'http://localhost:23657'
grpc_addr = 'http://localhost:9040'
websocket_addr = 'ws://localhost:23657/websocket'
rpc_timeout = '10s'
account_prefix = 'osmo'
key_name = 'osmo'
store_prefix = 'ibc'
default_gas = 100000
max_gas = 3000000
gas_price = { price = 0.000, denom = 'uosmo' }
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
max_block_time = '10s'
trusting_period = '180s'
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'cosmos' }


[[chains]]
id = 'osmo-test-4'
rpc_addr = 'https://rpc-test.osmosis.zone:443'
grpc_addr = 'http://grpc-test.osmosis.zone:9090'
websocket_addr = 'wss://rpc-test.osmosis.zone/websocket'
rpc_timeout = '10s'
account_prefix = 'osmo'
key_name = 'osmo'
store_prefix = 'ibc'
default_gas = 100000
max_gas = 3000000
gas_price = { price = 0.000, denom = 'uosmo' }
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
max_block_time = '10s'
trusting_period = '180s'
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'cosmos' }
[chains.packet_filter]
policy = 'allow'
list = [
  ['ica*', '*'], # allow relaying on all channels whose port starts with `ica`
  ['transfer', 'channel-417'],
]