FROM golang:1.17-alpine3.15 AS icq-builder

RUN apk add --update git iputils

WORKDIR /src/app

RUN git clone https://github.com/Stride-Labs/interchain-queries.git \
    && cp -r interchain-queries/* . \
    && rm -rf interchain-queries \
    && go build

FROM alpine:3.15

COPY --from=icq-builder /src/app/interchain-queries /usr/local/bin/

RUN apk add --update iputils \
    && adduser -S -h /icq -D icq -u 1000 

USER icq
WORKDIR /icq