<Release Title>

# 🔨 Build from source
```
git clone https://github.com/Stride-Labs/stride/v2
cd stride && git checkout v1.0.0
make build
```

# ⚡️ Download binaries
Binaries for linux amd64 and arm64 are available below.