accounts:
  - name: alice
    coins: ["20000token", "200000000stake", "25000ibc/token"]
  - name: bob
    coins: ["10000token", "100000000stake", "5000ibc/C4CFF46FD6DE35CA4CF4CE031E643C8FDC9BA4B99AE598E9B0ED98FE3A2319F9"]
validator:
  name: alice
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5token", "100000stake"]
