FROM golang:1.17-alpine3.15 AS gaiad-builder

WORKDIR /src/app/

RUN apk add --update curl make git libc-dev bash gcc linux-headers eudev-dev python3

RUN git clone https://github.com/Stride-Labs/gaia --branch v7.0.2-pin-ibc-cosmos-sdk \
    && cd gaia \
    && CGO_ENABLED=0 make install

FROM alpine:3.15
COPY --from=gaiad-builder /go/bin/gaiad /usr/local/bin/
RUN adduser -S -h /home/gaia -D gaia -u 1000

USER gaia
WORKDIR /home/gaia

EXPOSE 26657 26656 1317 9090

CMD ["gaiad", "start"]
