FROM golang:1.17-alpine3.15 AS icq-builder

RUN apk add --upgrade git

WORKDIR /src/app

RUN git clone https://github.com/Stride-Labs/interchain-queries.git \
    && cp -r interchain-queries/* . \
    && rm -rf interchain-queries \
    && go build

FROM alpine:3.15

COPY --from=icq-builder /src/app/interchain-queries /usr/local/bin/

RUN adduser -S -h /home/icq -D icq -u 1000
USER icq

WORKDIR /home/icq

CMD ["interchain-queries", "run"]