FROM golang:1.18-alpine3.15 AS builder

WORKDIR /src/

RUN apk add --update git make gcc linux-headers libc-dev eudev-dev 
RUN git clone https://github.com/cosmos/relayer.git \
    && cd relayer \
    && git checkout v2.0.0 \
    && make install

FROM alpine:3.15
COPY --from=builder /go/bin/rly /usr/local/bin/
RUN adduser -S -h /home/relayer -D relayer -u 1000

USER relayer
WORKDIR /home/relayer

CMD ["rly", "start", "stride-gaia"]
