FROM golang:1.17-alpine3.15 AS golang

WORKDIR /src/app/
COPY go.mod go.sum* ./
RUN go mod download
COPY . .

RUN apk add --no-cache make git gcc musl-dev openssl-dev linux-headers 
RUN make build

# Add to a distroless container
FROM alpine:3.15
COPY --from=golang /src/app/build/strided /usr/local/bin/strided
RUN adduser -S -h /stride -D stride -u 1000
USER stride

RUN strided init test
CMD ["strided", "start", "--home", "stride/.strided"]
