#!/bin/bash

SCRIPTS_DIR=scripts
SHARED_DIR=shared
CONFIG_DIR=config

VALIDATOR_KEYS_DIR=${SHARED_DIR}/validator-keys
NODE_KEYS_DIR=${SHARED_DIR}/node-keys
NODE_IDS_DIR=${SHARED_DIR}/node-ids
KEYS_FILE=${CONFIG_DIR}/keys.json

POD_INDEX=${HOSTNAME##*-}
VALIDATOR_INDEX=$((POD_INDEX+1))
VALIDATOR_NAME=val${VALIDATOR_INDEX}

PEER_PORT=26656
RPC_PORT=26657

CHAIN_NAME=stride
BINARY=strided
DENOM=ustrd
MICRO_DENOM_UNITS=000000
CHAIN_HOME=.stride
NUM_VALIDATORS=3

CHAIN_ID=${CHAIN_NAME}-test-1
BLOCK_TIME=1s
VALIDATOR_BALANCE=10000000${MICRO_DENOM_UNITS}
VALIDATOR_STAKE=1000000${MICRO_DENOM_UNITS}

STRIDE_DAY_EPOCH_DURATION="140s"
STRIDE_EPOCH_EPOCH_DURATION="35s"
MAX_DEPOSIT_PERIOD="30s"
VOTING_PERIOD="30s"
UNBONDING_TIME="240s"
