version: "3"
services:
  stride1:
    image: stridezone:stride
    volumes:
      - ./state/stride1:/home/stride/.stride
    ports:
      - "26657:26657"
      - "1317:1317"
      - "9090:9090"

  stride2:
    image: stridezone:stride
    volumes:
      - ./state/stride2:/home/stride/.stride

  stride3:
    image: stridezone:stride
    volumes:
      - ./state/stride3:/home/stride/.stride

  gaia1:
    image: stridezone:gaia
    volumes:
      - ./state/gaia1:/home/gaia/.gaia
    ports:
      - "26557:26657"
      - "1307:1317"
      - "9080:9090"

  gaia2:
    image: stridezone:gaia
    volumes:
      - ./state/gaia2:/home/gaia/.gaia

  gaia3:
    image: stridezone:gaia
    volumes:
      - ./state/gaia3:/home/gaia/.gaia

  gaia4:
    image: stridezone:gaia
    volumes:
      - ./state/gaia4:/home/gaia/.gaia

  gaia5:
    image: stridezone:gaia
    volumes:
      - ./state/gaia5:/home/gaia/.gaia

  juno1:
    image: stridezone:juno
    volumes:
      - ./state/juno1:/home/juno/.juno
    ports:
      - "26457:26657"
      - "1297:1317"
      - "9070:9090"

  juno2:
    image: stridezone:juno
    volumes:
      - ./state/juno2:/home/juno/.juno

  juno3:
    image: stridezone:juno
    volumes:
      - ./state/juno3:/home/juno/.juno

  juno4:
    image: stridezone:juno
    volumes:
      - ./state/juno4:/home/juno/.juno

  juno5:
    image: stridezone:juno
    volumes:
      - ./state/juno5:/home/juno/.juno

  osmo1:
    image: stridezone:osmo
    volumes:
      - ./state/osmo1:/home/osmosis/.osmosisd
    ports:
      - "26357:26657"
      - "1287:1317"
      - "9060:9090"

  osmo2:
    image: stridezone:osmo
    volumes:
      - ./state/osmo2:/home/osmosis/.osmosisd

  osmo3:
    image: stridezone:osmo
    volumes:
      - ./state/osmo3:/home/osmosis/.osmosisd

  osmo4:
    image: stridezone:osmo
    volumes:
      - ./state/osmo4:/home/osmosis/.osmosisd

  osmo5:
    image: stridezone:osmo
    volumes:
      - ./state/osmo5:/home/osmosis/.osmosisd

  stars1:
    image: stridezone:stars
    volumes:
      - ./state/stars1:/home/stars/.starsd
    ports:
      - "26257:26657"
      - "1277:1317"
      - "9050:9090"

  stars2:
    image: stridezone:stars
    volumes:
      - ./state/stars2:/home/stars/.starsd

  stars3:
    image: stridezone:stars
    volumes:
      - ./state/stars3:/home/stars/.starsd

  stars4:
    image: stridezone:stars
    volumes:
      - ./state/stars4:/home/stars/.starsd

  stars5:
    image: stridezone:stars
    volumes:
      - ./state/stars5:/home/stars/.starsd

  # For the host chain, we must override the command to prevent an old binary from
  # being run when testing upgrades
  host1:
    image: stridezone:stride
    command: strided start
    volumes:
      - ./state/host1:/home/stride/.stride
    ports:
      - "26157:26657"
      - "1267:1317"
      - "9040:9090"

  host2:
    image: stridezone:stride
    command: strided start
    volumes:
      - ./state/host2:/home/stride/.stride

  host3:
    image: stridezone:stride
    command: strided start
    volumes:
      - ./state/host3:/home/stride/.stride

  host4:
    image: stridezone:stride
    command: strided start
    volumes:
      - ./state/host4:/home/stride/.stride

  host5:
    image: stridezone:stride
    command: strided start
    volumes:
      - ./state/host5:/home/stride/.stride

  evmos1:
    image: stridezone:evmos
    volumes:
      - ./state/evmos1:/home/evmos/.evmosd
    ports:
      - "26057:26657"
      - "1257:1317"
      - "9030:9090"

  evmos2:
    image: stridezone:evmos
    volumes:
      - ./state/evmos2:/home/evmos/.evmosd

  evmos3:
    image: stridezone:evmos
    volumes:
      - ./state/evmos3:/home/evmos/.evmosd

  evmos4:
    image: stridezone:evmos
    volumes:
      - ./state/evmos4:/home/evmos/.evmosd

  evmos5:
    image: stridezone:evmos
    volumes:
      - ./state/evmos5:/home/evmos/.evmosd

  dydx1:
    image: stridezone:dydx
    volumes:
      - ./state/dydx1:/home/dydx/.dydxprotocol
    ports:
      - "25957:26657"
      - "1247:1317"
      - "9020:9090"

  dydx2:
    image: stridezone:dydx
    volumes:
      - ./state/dydx2:/home/dydx/.dydxprotocol

  dydx3:
    image: stridezone:dydx
    volumes:
      - ./state/dydx3:/home/dydx/.dydxprotocol

  dydx4:
    image: stridezone:dydx
    volumes:
      - ./state/dydx4:/home/dydx/.dydxprotocol

  dydx5:
    image: stridezone:dydx
    volumes:
      - ./state/dydx5:/home/dydx/.dydxprotocol

  noble1:
    image: stridezone:noble
    volumes:
      - ./state/noble1:/home/noble/.noble
    ports:
      - "25857:26657"
      - "1237:1317"
      - "9010:9090"

  noble2:
    image: stridezone:noble
    volumes:
      - ./state/noble2:/home/noble/.noble

  noble3:
    image: stridezone:noble
    volumes:
      - ./state/noble3:/home/noble/.noble

  noble4:
    image: stridezone:noble
    volumes:
      - ./state/noble4:/home/noble/.noble

  noble5:
    image: stridezone:noble
    volumes:
      - ./state/noble5:/home/noble/.noble

  # Fill in new host zone being tested here

  hermes:
    image: stridezone:hermes
    volumes:
      - ~/.hermes:/home/hermes/.hermes
      - ./state/hermes/config.toml:/home/hermes/.hermes/config.toml
    restart: always

  relayer-gaia:
    image: stridezone:relayer
    volumes:
      - ./state/relayer-gaia:/home/relayer/.relayer
    restart: always
    command: [ "bash", "start.sh", "stride-gaia" ]

  relayer-gaia-ics:
    image: stridezone:relayer
    volumes:
      - ./state/relayer-gaia-ics:/home/relayer/.relayer
    restart: always
    command: [ "bash", "start.sh", "stride-gaia-ics" ]

  relayer-juno:
    image: stridezone:relayer
    volumes:
      - ./state/relayer-juno:/home/relayer/.relayer
    restart: always
    command: [ "bash", "start.sh", "stride-juno" ]

  relayer-osmo:
    image: stridezone:relayer
    volumes:
      - ./state/relayer-osmo:/home/relayer/.relayer
    restart: always
    command: [ "bash", "start.sh", "stride-osmo" ]

  relayer-stars:
    image: stridezone:relayer
    volumes:
      - ./state/relayer-stars:/home/relayer/.relayer
    restart: always
    command: [ "bash", "start.sh", "stride-stars" ]

  relayer-host:
    image: stridezone:relayer
    volumes:
      - ./state/relayer-host:/home/relayer/.relayer
    restart: always
    command: [ "bash", "start.sh", "stride-host" ]

  relayer-evmos:
    image: stridezone:relayer
    volumes:
      - ./state/relayer-evmos:/home/relayer/.relayer
    restart: always
    command: [ "bash", "start.sh", "stride-evmos" ]

  relayer-dydx:
    image: stridezone:relayer
    volumes:
      - ./state/relayer-dydx:/home/relayer/.relayer
    restart: always
    command: [ "bash", "start.sh", "stride-dydx" ]

  relayer-juno-osmo:
    image: stridezone:relayer
    volumes:
      - ./state/relayer-juno-osmo:/home/relayer/.relayer
    restart: always
    command: [ "bash", "start.sh", "juno-osmo" ]

  relayer-dydx-noble:
    image: stridezone:relayer
    volumes:
      - ./state/relayer-dydx-noble:/home/relayer/.relayer
    restart: always
    command: [ "bash", "start.sh", "dydx-noble" ]

  relayer-noble-osmo:
    image: stridezone:relayer
    volumes:
      - ./state/relayer-noble-osmo:/home/relayer/.relayer
    restart: always
    command: [ "bash", "start.sh", "noble-osmo" ]

  relayer-osmo-dydx:
    image: stridezone:relayer
    volumes:
      - ./state/relayer-osmo-dydx:/home/relayer/.relayer
    restart: always
    command: [ "bash", "start.sh", "osmo-dydx" ]
