version: "3"
services:
  stride1:
    image: stridezone:stride
    volumes:
      - ./state/stride1:/home/stride/.stride
    ports:
      - "26657:26657"
      - "1317:1317"
      - "9090:9090"

  stride2:
    image: stridezone:stride
    volumes:
      - ./state/stride2:/home/stride/.stride

  stride3:
    image: stridezone:stride
    volumes:
      - ./state/stride3:/home/stride/.stride

  gaia1:
    image: stridezone:gaia
    volumes:
      - ./state/gaia1:/home/gaia/.gaia
    ports:
      - "26557:26657"
      - "1307:1317"
      - "9080:9090"

  gaia2:
    image: stridezone:gaia
    volumes:
      - ./state/gaia2:/home/gaia/.gaia

  gaia3:
    image: stridezone:gaia
    volumes:
      - ./state/gaia3:/home/gaia/.gaia

  gaia4:
    image: stridezone:gaia
    volumes:
      - ./state/gaia4:/home/gaia/.gaia

  gaia5:
    image: stridezone:gaia
    volumes:
      - ./state/gaia5:/home/gaia/.gaia

  juno1:
    image: stridezone:juno
    volumes:
      - ./state/juno1:/home/juno/.juno
    ports:
      - "26457:26657"
      - "1297:1317"
      - "9070:9090"

  juno2:
    image: stridezone:juno
    volumes:
      - ./state/juno2:/home/juno/.juno

  juno3:
    image: stridezone:juno
    volumes:
      - ./state/juno3:/home/juno/.juno

  juno4:
    image: stridezone:juno
    volumes:
      - ./state/juno4:/home/juno/.juno

  juno5:
    image: stridezone:juno
    volumes:
      - ./state/juno5:/home/juno/.juno

  osmo1:
    image: stridezone:osmo
    volumes:
      - ./state/osmo1:/home/osmosis/.osmosisd
    ports:
      - "26357:26657"
      - "1287:1317"
      - "9060:9090"

  osmo2:
    image: stridezone:osmo
    volumes:
      - ./state/osmo2:/home/osmosis/.osmosisd

  osmo3:
    image: stridezone:osmo
    volumes:
      - ./state/osmo3:/home/osmosis/.osmosisd

  osmo4:
    image: stridezone:osmo
    volumes:
      - ./state/osmo4:/home/osmosis/.osmosisd

  osmo5:
    image: stridezone:osmo
    volumes:
      - ./state/osmo5:/home/osmosis/.osmosisd

  stars1:
    image: stridezone:stars
    volumes:
      - ./state/stars1:/home/stars/.starsd
    ports:
      - "26257:26657"
      - "1277:1317"
      - "9050:9090"

  stars2:
    image: stridezone:stars
    volumes:
      - ./state/stars2:/home/stars/.starsd

  stars3:
    image: stridezone:stars
    volumes:
      - ./state/stars3:/home/stars/.starsd

  stars4:
    image: stridezone:stars
    volumes:
      - ./state/stars4:/home/stars/.starsd

  stars5:
    image: stridezone:stars
    volumes:
      - ./state/stars5:/home/stars/.starsd

  hermes:
    image: stridezone:hermes
    volumes:
      - ~/.hermes:/home/hermes/.hermes
      - ./state/hermes/config.toml:/home/hermes/.hermes/config.toml
    restart: always

  relayer-gaia:
    image: stridezone:relayer
    volumes:
      - ./state/relayer-gaia:/home/relayer/.relayer
    restart: always
    command: [ "bash", "start.sh", "stride-gaia" ]

  relayer-juno:
    image: stridezone:relayer
    volumes:
      - ./state/relayer-juno:/home/relayer/.relayer
    restart: always
    command: [ "bash", "start.sh", "stride-juno" ]

  relayer-osmo:
    image: stridezone:relayer
    volumes:
      - ./state/relayer-osmo:/home/relayer/.relayer
    restart: always
    command: [ "bash", "start.sh", "stride-osmo" ]

  relayer-stars:
    image: stridezone:relayer
    volumes:
      - ./state/relayer-stars:/home/relayer/.relayer
    restart: always
    command: [ "bash", "start.sh", "stride-stars" ]
