version: "3"
services:
  stride1:
    image: stridezone:stride-debug
    volumes:
      - ./state/stride1:/home/stride/.stride
    ports:
      - "26657:26657"
      - "1317:1317"
      - "9090:9090"
      - "2345:2345"
    command: "/usr/local/bin/dlv --listen=:2345 --headless=true --log=true --log-output=debugger,debuglineerr,gdbwire,lldbout --accept-multiclient --api-version=2 exec /usr/local/bin/strided -- start"
