global:
  api-listen-addr: :5183
  timeout: 10s
  memo: ""
  light-cache-size: 20
chains:
  consumer:
    type: cosmos
    value:
      key-directory: relayer/keys/consumer
      key: rly2
      chain-id: consumer
      rpc-addr: http://127.0.0.1:26638
      account-prefix: stride
      keyring-backend: test
      gas-adjustment: 1.2
      gas-prices: 0.00stake
      min-gas-amount: 0
      debug: false
      timeout: 20s
      block-timeout: ""
      output-format: json
      sign-mode: direct
      extra-codecs: []
      coin-type: null
      broadcast-mode: batch
  provider:
    type: cosmos
    value:
      key-directory: relayer/keys/provider
      key: rly1
      chain-id: provider
      rpc-addr: http://127.0.0.1:26658
      account-prefix: cosmos
      keyring-backend: test
      gas-adjustment: 1.2
      gas-prices: 0.00stake
      min-gas-amount: 0
      debug: false
      timeout: 20s
      block-timeout: ""
      output-format: json
      sign-mode: direct
      extra-codecs: []
      coin-type: null
      broadcast-mode: batch
paths:
  consumer-provider:
    src:
      chain-id: consumer
    dst:
      chain-id: provider
    src-channel-filter:
      rule: ""
      channel-list: []
  consumer-provider-ics:
    src:
      chain-id: consumer
      client-id: 07-tendermint-1
    dst:
      chain-id: provider
      client-id: 07-tendermint-1
    src-channel-filter:
      rule: ""
      channel-list: []
