global:
    api-listen-addr: :5183
    debug-listen-addr: ""
    metrics-listen-addr: ""
    timeout: 10s
    memo: stride-tests
    light-cache-size: 20
    log-level: ""
    ics20-memo-limit: 0
    max-receiver-size: 0
chains:
    osmosis:
        type: cosmos
        value:
            key-directory: relayer/keys/osmosis-1
            key: osmosis
            chain-id: osmosis-1
            rpc-addr: https://osmosis-strd-rpc.polkachu.com:443
            backup-rpc-addrs: []
            account-prefix: osmo
            keyring-backend: test
            dynamic-gas-price: false
            gas-adjustment: 1.3
            gas-prices: 0.02uosmo
            min-gas-amount: 0
            max-gas-amount: 0
            debug: false
            timeout: 60s
            block-timeout: ""
            output-format: json
            sign-mode: direct
            extra-codecs: []
            coin-type: 118
            signing-algorithm: ""
            broadcast-mode: batch
            min-loop-duration: 5s
            extension-options: []
            feegrants: null
    stride:
        type: cosmos
        value:
            key-directory: relayer/keys/stride-test-1
            key: stride
            chain-id: stride-test-1
            rpc-addr: https://stride-rpc.internal.stridenet.co:443
            backup-rpc-addrs: []
            account-prefix: stride
            keyring-backend: test
            dynamic-gas-price: false
            gas-adjustment: 1.3
            gas-prices: 1ustrd
            min-gas-amount: 0
            max-gas-amount: 0
            debug: false
            timeout: 20s
            block-timeout: ""
            output-format: json
            sign-mode: direct
            extra-codecs: []
            coin-type: 118
            signing-algorithm: ""
            broadcast-mode: batch
            min-loop-duration: 1s
            extension-options: []
            feegrants: null
paths:
    stride-osmosis:
        src:
            chain-id: stride-test-1
        dst:
            chain-id: osmosis-1
        src-channel-filter:
            rule: ""
            channel-list: []
