package types

import errorsmod "cosmossdk.io/errors"

var (
	ErrHostZoneNotFound                  = errorsmod.Register(ModuleName, 1901, "host zone not found")
	ErrDelegationRecordNotFound          = errorsmod.Register(ModuleName, 1902, "delegation record not found")
	ErrUnbondingRecordNotFound           = errorsmod.Register(ModuleName, 1903, "unbonding record not found")
	ErrRedemptionRecordNotFound          = errorsmod.Register(ModuleName, 1904, "redemption record not found")
	ErrBrokenUnbondingRecordInvariant    = errorsmod.Register(ModuleName, 1905, "broken unbonding record invariant")
	ErrRedemptionRateOutsideSafetyBounds = errorsmod.Register(ModuleName, 1906, "host zone redemption rate outside safety bounds")
	ErrInvalidRedemptionRateBounds       = errorsmod.Register(ModuleName, 1907, "invalid host zone redemption rate inner bounds")
	ErrHostZoneHalted                    = errorsmod.Register(ModuleName, 1908, "host zone is halted")
	ErrInvalidAmountBelowMinimum         = errorsmod.Register(ModuleName, 1909, "amount provided is too small")
	ErrInvalidBounds                     = errorsmod.Register(ModuleName, 1910, "invalid inner bounds")
	ErrInvalidAdmin                      = errorsmod.Register(ModuleName, 1911, "signer is not an admin")
	ErrDelegationRecordInvalidState      = errorsmod.Register(ModuleName, 1912, "delegation record in incorrect state")
	ErrInvalidArgument                   = errorsmod.Register(ModuleName, 1913, "argument is not valid")
	ErrHostZoneNotHalted                 = errorsmod.Register(ModuleName, 1914, "host zone is not halted")
	ErrDelegationRecordAlreadyExists     = errorsmod.Register(ModuleName, 1915, "delegation record already exists")
	ErrInvariantBroken                   = errorsmod.Register(ModuleName, 1916, "invariant broken")
	ErrUnbondAmountToLarge               = errorsmod.Register(ModuleName, 1917, "unbonding more than exists on host zone")
	ErrUnbondingRecordAlreadyExists      = errorsmod.Register(ModuleName, 1918, "unbonding record already exists")
	ErrInvalidRecordType                 = errorsmod.Register(ModuleName, 1919, "invalid record type")
	ErrInvalidUnbondingRecord            = errorsmod.Register(ModuleName, 1920, "invalid unbonding record")
	ErrInsufficientFunds                 = errorsmod.Register(ModuleName, 1921, "insufficient funds")
	ErrInvalidTxHash                     = errorsmod.Register(ModuleName, 1922, "tx hash is invalid")
	ErrInvalidHostZone                   = errorsmod.Register(ModuleName, 1923, "invalid host zone during genesis")
	ErrInvalidGenesisRecords             = errorsmod.Register(ModuleName, 1924, "invalid records during genesis")
)
