version: "3"
services:
  stride1:
    image: stridezone:stride
    volumes:
      - ../state/stride1:/home/stride/.stride
    ports:
      - "26657:26657"
      - "1317:1317"
      - "9090:9090"

  hermes:
    image: stridezone:hermes
    volumes:
      - ~/.hermes:/home/hermes/.hermes
      - ../state/hermes/config.toml:/home/hermes/.hermes/config.toml
    restart: always

  relayer:
    image: stridezone:relayer
    volumes:
      - ../state/relayer:/home/relayer/.relayer
    restart: always
    command: [ "bash", "start.sh", "stride-host" ]
