package types

// DONTCOVER

import (
	"fmt"
)

// x/stakeibc module sentinel errors
var (
	ErrInvalidVersion                    = fmt.Errorf("invalid version")
	ErrInvalidToken                      = fmt.Errorf("invalid token denom")
	ErrInvalidHostZone                   = fmt.Errorf("host zone not registered")
	ErrICAStake                          = fmt.Errorf("ICA stake failed")
	ErrEpochNotFound                     = fmt.Errorf("epoch not found")
	ErrRecordNotFound                    = fmt.Errorf("record not found")
	ErrInvalidAmount                     = fmt.Errorf("invalid amount")
	ErrValidatorAlreadyExists            = fmt.Errorf("validator already exists")
	ErrNoValidatorWeights                = fmt.Errorf("no non-zero validator weights")
	ErrValidatorNotFound                 = fmt.Errorf("validator not found")
	ErrWeightsNotDifferent               = fmt.Errorf("validator weights haven't changed")
	ErrValidatorDelegationChg            = fmt.Errorf("can't change delegation on validator")
	ErrAcctNotScopedForFunc              = fmt.Errorf("this account can't call this function")
	ErrInsufficientFunds                 = fmt.Errorf("balance is insufficient")
	ErrInvalidUserRedemptionRecord       = fmt.Errorf("user redemption record error")
	ErrRequiredFieldEmpty                = fmt.Errorf("required field is missing")
	ErrInvalidNumValidator               = fmt.Errorf("invalid number of validators")
	ErrValidatorNotRemoved               = fmt.Errorf("validator not removed")
	ErrHostZoneNotFound                  = fmt.Errorf("host zone not found")
	ErrUndelegationAmount                = fmt.Errorf("undelegation amount is invalid")
	ErrOutsideIcqWindow                  = fmt.Errorf("outside time window that accepts icqs")
	ErrParamNotFound                     = fmt.Errorf("param not found")
	ErrUnmarshalFailure                  = fmt.Errorf("unable to unmarshal data structure")
	ErrMarshalFailure                    = fmt.Errorf("unable to marshal data structure")
	ErrInvalidPacketCompletionTime       = fmt.Errorf("invalid packet completion time")
	ErrIntCast                           = fmt.Errorf("unable to cast to safe cast int")
	ErrFeeAccountNotRegistered           = fmt.Errorf("fee account is not registered")
	ErrRedemptionRateOutsideSafetyBounds = fmt.Errorf("redemption rate outside safety bounds")
	ErrTxMsgDataInvalid                  = fmt.Errorf("TxMsgData invalid")
	ErrFailedToRegisterHostZone          = fmt.Errorf("failed to register host zone")
	ErrInvalidInterchainAccountAddress   = fmt.Errorf("invalid interchain account address")
	ErrICAAccountNotFound                = fmt.Errorf("ICA acccount not found on host zone")
	ErrICATxFailed                       = fmt.Errorf("failed to submit ICA transaction")
	ErrICQFailed                         = fmt.Errorf("failed to submit ICQ")
	ErrDivisionByZero                    = fmt.Errorf("division by zero")
	ErrSlashGtTenPct                     = fmt.Errorf("slash is greater than 10 percent")
	ErrInvalidEpoch                      = fmt.Errorf("invalid epoch tracker")
	ErrHostZoneICAAccountNotFound        = fmt.Errorf("host zone's ICA account not found")
	ErrNoValidatorAmts                   = fmt.Errorf("could not fetch validator amts")
	ErrMaxNumValidators                  = fmt.Errorf("max number of validators reached")
	ErrKeyNotFound                       = fmt.Errorf("key not found")
	ErrInvalidAddress                    = fmt.Errorf("invalid address")
)
