default_chain: stride
chains:
  stride:
    key: icq1
    chain-id: STRIDE_CHAIN_ID
    rpc-addr: http://STRIDE_ENDPOINT:26657
    grpc-addr: http://STRIDE_ENDPOINT:9090
    account-prefix: stride
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 1ustrd
    key-directory: /icq/keys
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
  gaia:
    key: icq2
    chain-id: GAIA
    rpc-addr: http://GAIA_ENDPOINT:26657
    grpc-addr: http://GAIA_ENDPOINT:9090
    account-prefix: cosmos
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 1uatom
    key-directory: /icq/keys
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
