FROM golang:1.22-alpine AS builder

WORKDIR /opt

RUN apk add --update curl make git libc-dev bash gcc linux-headers eudev-dev ca-certificates build-base git

ENV REPO=https://github.com/cosmos/gaia
ENV COMMIT_HASH=v18.1.0
ENV BINARY=gaiad

RUN git clone ${REPO} chain \
    && cd chain \
    && git checkout $COMMIT_HASH 
    
WORKDIR /opt/chain

RUN WASMVM_VERSION=$(cat go.mod | grep github.com/CosmWasm/wasmvm | awk '{print $2}') \
    && wget https://github.com/CosmWasm/wasmvm/releases/download/$WASMVM_VERSION/libwasmvm_muslc.$(uname -m).a \
    -O /lib/libwasmvm_muslc.a

RUN CGO_ENABLED=1 BUILD_TAGS="muslc linkstatic" LINK_STATICALLY=true LEDGER_ENABLED=false make install

FROM alpine:3.17
COPY --from=builder /go/bin/$BINARY /usr/local/bin/
RUN apk add bash vim \
    && addgroup -g 1000 validator \
    && adduser -S -h /home/validator -D validator -u 1000 -G validator

USER 1000
WORKDIR /home/validator

EXPOSE 26657 26656 1317 9090

CMD ["$BINARY", "start"]
