FROM rust:1.71-buster as builder

# REHEARSAL ONLY: hermes >= 1.10 understands CometBFT 0.38+ event encoding (compat_mode 0.38)
COPY --from=informalsystems/hermes:1.13.1 /usr/bin/hermes /usr/bin/hermes

RUN apt-get update \
    && apt-get install -y iputils-ping ca-certificates libssl-dev bash vim curl jq \
    && addgroup --gid 1000 hermes \
    && adduser --system --home /home/hermes --disabled-password --disabled-login \
    --uid 1000 --ingroup hermes hermes

USER hermes
WORKDIR /home/hermes

CMD ["bash", "scripts/start-hermes.sh"]