FROM golang:1.23-alpine3.21 AS builder

WORKDIR /opt

RUN apk add --update curl make git libc-dev bash gcc linux-headers eudev-dev ca-certificates build-base git 

ENV REPO=https://github.com/osmosis-labs/osmosis
ENV COMMIT_HASH=v27.0.0
ENV BINARY=osmosisd

RUN git clone ${REPO} chain \
    && cd chain \
    && git checkout $COMMIT_HASH 
    
WORKDIR /opt/chain

RUN ARCH=$(uname -m) && WASMVM_VERSION=$(go list -m github.com/CosmWasm/wasmvm/v2 | sed 's/.* //') && \
    wget https://github.com/CosmWasm/wasmvm/releases/download/$WASMVM_VERSION/libwasmvm_muslc.$ARCH.a \
    -O /lib/libwasmvm_muslc.$ARCH.a

RUN BUILD_TAGS=muslc LINK_STATICALLY=true make install

FROM alpine:3.21
COPY --from=builder /go/bin/$BINARY /usr/local/bin/
RUN apk add bash vim sudo dasel jq curl \
    && addgroup -g 1000 validator \
    && adduser -S -h /home/validator -D validator -u 1000 -G validator

USER 1000
WORKDIR /home/validator

EXPOSE 26657 26656 1317 9090
