FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y gcc g++ bash vim git curl tzdata \
    && adduser --system --home /home/python --disabled-password --disabled-login python -u 1000 \
    && pip install --upgrade pip

COPY ./requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY main.py main.py

CMD ["uvicorn", "main:app", "--proxy-headers", "--host", "0.0.0.0"]
