FROM golang:1.21-alpine3.17 AS builder

WORKDIR /src/

ENV COMMIT_HASH=v2.5.2

RUN apk add --update git make gcc linux-headers libc-dev eudev-dev 
RUN git clone https://github.com/cosmos/relayer.git \
    && cd relayer \
    && git checkout ${COMMIT_HASH} \
    && CGO_ENABLED=1 LDFLAGS='-linkmode external -extldflags "-static"' make install

FROM alpine:3.17

COPY --from=builder /go/bin/rly /usr/local/bin/
RUN apk add --no-cache --update bash vim curl iputils jq yq \
    && addgroup -g 1000 relayer \
    && adduser -S -h /home/relayer -D relayer -u 1000 -G relayer 

USER relayer
WORKDIR /home/relayer

CMD ["bash", "scripts/start-relayer.sh"]