// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: stride/icqoracle/icqoracle.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	_ "github.com/cosmos/gogoproto/types"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// TokenPrice stores latest price data for a token
type TokenPrice struct {
	// Token denom (e.g. "uatom", "uosmo")
	BaseDenom string `protobuf:"bytes,1,opt,name=base_denom,json=baseDenom,proto3" json:"base_denom,omitempty"`
	// Quote denom (e.g. ustrd, uusdc)
	QuoteDenom string `protobuf:"bytes,2,opt,name=quote_denom,json=quoteDenom,proto3" json:"quote_denom,omitempty"`
	// Price in USDC or STRD
	Price cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=price,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"price"`
	// Last update timestamp
	UpdatedAt time.Time `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3,stdtime" json:"updated_at"`
	// Whether there is a price query currently in progress
	QueryInProgress bool `protobuf:"varint,5,opt,name=query_in_progress,json=queryInProgress,proto3" json:"query_in_progress,omitempty"`
}

func (m *TokenPrice) Reset()         { *m = TokenPrice{} }
func (m *TokenPrice) String() string { return proto.CompactTextString(m) }
func (*TokenPrice) ProtoMessage()    {}
func (*TokenPrice) Descriptor() ([]byte, []int) {
	return fileDescriptor_08ead8ab9516d7fc, []int{0}
}
func (m *TokenPrice) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TokenPrice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TokenPrice.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TokenPrice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenPrice.Merge(m, src)
}
func (m *TokenPrice) XXX_Size() int {
	return m.Size()
}
func (m *TokenPrice) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenPrice.DiscardUnknown(m)
}

var xxx_messageInfo_TokenPrice proto.InternalMessageInfo

func (m *TokenPrice) GetBaseDenom() string {
	if m != nil {
		return m.BaseDenom
	}
	return ""
}

func (m *TokenPrice) GetQuoteDenom() string {
	if m != nil {
		return m.QuoteDenom
	}
	return ""
}

func (m *TokenPrice) GetUpdatedAt() time.Time {
	if m != nil {
		return m.UpdatedAt
	}
	return time.Time{}
}

func (m *TokenPrice) GetQueryInProgress() bool {
	if m != nil {
		return m.QueryInProgress
	}
	return false
}

// OracleParams stores global oracle parameters
type Params struct {
	// Osmosis chain identifier
	OsmosisChainId string `protobuf:"bytes,1,opt,name=osmosis_chain_id,json=osmosisChainId,proto3" json:"osmosis_chain_id" yaml:"osmosis_chain_id"`
	// Osmosis IBC connection identifier
	OsmosisConnectionId string `protobuf:"bytes,2,opt,name=osmosis_connection_id,json=osmosisConnectionId,proto3" json:"osmosis_connection_id" yaml:"osmosis_connection_id"`
	// Time between price updates
	UpdateIntervalSec uint64 `protobuf:"varint,3,opt,name=update_interval_sec,json=updateIntervalSec,proto3" json:"update_interval_sec" yaml:"update_interval_sec"`
	// Max time before price is stale
	TimeoutSec uint64 `protobuf:"varint,4,opt,name=timeout_sec,json=timeoutSec,proto3" json:"timeout_sec" yaml:"timeout_sec"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_08ead8ab9516d7fc, []int{1}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetOsmosisChainId() string {
	if m != nil {
		return m.OsmosisChainId
	}
	return ""
}

func (m *Params) GetOsmosisConnectionId() string {
	if m != nil {
		return m.OsmosisConnectionId
	}
	return ""
}

func (m *Params) GetUpdateIntervalSec() uint64 {
	if m != nil {
		return m.UpdateIntervalSec
	}
	return 0
}

func (m *Params) GetTimeoutSec() uint64 {
	if m != nil {
		return m.TimeoutSec
	}
	return 0
}

func init() {
	proto.RegisterType((*TokenPrice)(nil), "stride.icqoracle.TokenPrice")
	proto.RegisterType((*Params)(nil), "stride.icqoracle.Params")
}

func init() { proto.RegisterFile("stride/icqoracle/icqoracle.proto", fileDescriptor_08ead8ab9516d7fc) }

var fileDescriptor_08ead8ab9516d7fc = []byte{
	// 512 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0xc1, 0x6f, 0xd3, 0x30,
	0x14, 0xc6, 0x1b, 0xd6, 0x4d, 0xab, 0x2b, 0xc1, 0xe6, 0x81, 0xa8, 0x0a, 0xc4, 0x55, 0x10, 0x52,
	0x85, 0x44, 0x22, 0x6d, 0x70, 0x18, 0x37, 0xb2, 0x09, 0xa9, 0xd2, 0x90, 0xaa, 0x74, 0x17, 0xb8,
	0x44, 0xae, 0x63, 0x52, 0x6b, 0x4d, 0x9c, 0xc6, 0xce, 0x44, 0x8f, 0xfc, 0x07, 0xfb, 0xb3, 0x76,
	0xdc, 0x11, 0x71, 0x30, 0xa8, 0xbd, 0xf5, 0xd8, 0x13, 0x47, 0x14, 0x3b, 0xad, 0xaa, 0xad, 0x37,
	0xfb, 0xf7, 0x7d, 0xfe, 0xde, 0x8b, 0xf3, 0x0c, 0x3a, 0x42, 0xe6, 0x2c, 0xa2, 0x1e, 0x23, 0x13,
	0x9e, 0x63, 0x32, 0xde, 0x58, 0xb9, 0x59, 0xce, 0x25, 0x87, 0x07, 0xc6, 0xe1, 0xae, 0x79, 0xfb,
	0x69, 0xcc, 0x63, 0xae, 0x45, 0xaf, 0x5c, 0x19, 0x5f, 0x1b, 0xc5, 0x9c, 0xc7, 0x63, 0xea, 0xe9,
	0xdd, 0xb0, 0xf8, 0xee, 0x49, 0x96, 0x50, 0x21, 0x71, 0x92, 0x19, 0x83, 0xf3, 0xcf, 0x02, 0xe0,
	0x92, 0x5f, 0xd1, 0xb4, 0x9f, 0x33, 0x42, 0xe1, 0x2b, 0x00, 0x86, 0x58, 0xd0, 0x30, 0xa2, 0x29,
	0x4f, 0x5a, 0x56, 0xc7, 0xea, 0x36, 0x82, 0x46, 0x49, 0xce, 0x4b, 0x00, 0x11, 0x68, 0x4e, 0x0a,
	0x2e, 0x57, 0xfa, 0x23, 0xad, 0x03, 0x8d, 0x8c, 0xe1, 0x14, 0xec, 0x66, 0x65, 0x50, 0x6b, 0xa7,
	0x94, 0xfc, 0xd7, 0xb7, 0x0a, 0xd5, 0x7e, 0x2b, 0xf4, 0x82, 0x70, 0x91, 0x70, 0x21, 0xa2, 0x2b,
	0x97, 0x71, 0x2f, 0xc1, 0x72, 0xe4, 0x5e, 0xd0, 0x18, 0x93, 0xe9, 0x39, 0x25, 0x81, 0x39, 0x01,
	0xcf, 0x00, 0x28, 0xb2, 0x08, 0x4b, 0x1a, 0x85, 0x58, 0xb6, 0xea, 0x1d, 0xab, 0xdb, 0x3c, 0x6e,
	0xbb, 0xa6, 0x7f, 0x77, 0xd5, 0xbf, 0x7b, 0xb9, 0xea, 0xdf, 0xdf, 0x2f, 0xb3, 0x6f, 0xfe, 0x20,
	0x2b, 0x68, 0x54, 0xe7, 0x3e, 0x49, 0xf8, 0x16, 0x1c, 0x4e, 0x0a, 0x9a, 0x4f, 0x43, 0x96, 0x86,
	0x59, 0xce, 0xe3, 0x9c, 0x0a, 0xd1, 0xda, 0xed, 0x58, 0xdd, 0xfd, 0xe0, 0x89, 0x16, 0x7a, 0x69,
	0xbf, 0xc2, 0xce, 0xcf, 0x1d, 0xb0, 0xd7, 0xc7, 0x39, 0x4e, 0x04, 0xfc, 0x0a, 0x0e, 0x74, 0x83,
	0x4c, 0x84, 0x64, 0x84, 0x59, 0x1a, 0xb2, 0xc8, 0x7c, 0xbc, 0xef, 0x2d, 0x14, 0x7a, 0xa0, 0x2d,
	0x15, 0x7a, 0x3e, 0xc5, 0xc9, 0xf8, 0xa3, 0x73, 0x5f, 0x71, 0x82, 0xc7, 0x15, 0x3a, 0x2b, 0x49,
	0x2f, 0x82, 0x09, 0x78, 0xb6, 0x36, 0xf1, 0x34, 0xa5, 0x44, 0x32, 0xae, 0xf3, 0xf5, 0xe5, 0xf9,
	0xa7, 0x0b, 0x85, 0xb6, 0x1b, 0x96, 0x0a, 0xbd, 0xbc, 0x57, 0x64, 0x53, 0x76, 0x82, 0xa3, 0x55,
	0xa5, 0x35, 0xee, 0x45, 0x90, 0x82, 0x23, 0x73, 0x1b, 0x21, 0x4b, 0x25, 0xcd, 0xaf, 0xf1, 0x38,
	0x14, 0x94, 0xe8, 0xdf, 0x51, 0xf7, 0x3f, 0x2c, 0x14, 0xda, 0x26, 0x2f, 0x15, 0x6a, 0x9b, 0x52,
	0x5b, 0x44, 0x27, 0x38, 0x34, 0xb4, 0x57, 0xc1, 0x01, 0x25, 0xf0, 0x33, 0x68, 0x96, 0x93, 0xc4,
	0x0b, 0xa9, 0xe3, 0xeb, 0x3a, 0xfe, 0xcd, 0x42, 0xa1, 0x4d, 0xbc, 0x54, 0x08, 0x9a, 0xd8, 0x0d,
	0xe8, 0x04, 0xa0, 0xda, 0x0d, 0x28, 0xf1, 0xbf, 0xdc, 0xce, 0x6c, 0xeb, 0x6e, 0x66, 0x5b, 0x7f,
	0x67, 0xb6, 0x75, 0x33, 0xb7, 0x6b, 0x77, 0x73, 0xbb, 0xf6, 0x6b, 0x6e, 0xd7, 0xbe, 0x9d, 0xc4,
	0x4c, 0x8e, 0x8a, 0xa1, 0x4b, 0x78, 0xe2, 0x0d, 0xf4, 0xb0, 0xbf, 0xbb, 0xc0, 0x43, 0xe1, 0x55,
	0x4f, 0xe3, 0xfa, 0xf8, 0xbd, 0xf7, 0x63, 0xe3, 0x81, 0xc8, 0x69, 0x46, 0xc5, 0x70, 0x4f, 0xcf,
	0xc9, 0xc9, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0x78, 0xcc, 0x04, 0x81, 0x41, 0x03, 0x00, 0x00,
}

func (m *TokenPrice) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TokenPrice) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TokenPrice) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.QueryInProgress {
		i--
		if m.QueryInProgress {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.UpdatedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.UpdatedAt):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintIcqoracle(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x22
	{
		size := m.Price.Size()
		i -= size
		if _, err := m.Price.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintIcqoracle(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.QuoteDenom) > 0 {
		i -= len(m.QuoteDenom)
		copy(dAtA[i:], m.QuoteDenom)
		i = encodeVarintIcqoracle(dAtA, i, uint64(len(m.QuoteDenom)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.BaseDenom) > 0 {
		i -= len(m.BaseDenom)
		copy(dAtA[i:], m.BaseDenom)
		i = encodeVarintIcqoracle(dAtA, i, uint64(len(m.BaseDenom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TimeoutSec != 0 {
		i = encodeVarintIcqoracle(dAtA, i, uint64(m.TimeoutSec))
		i--
		dAtA[i] = 0x20
	}
	if m.UpdateIntervalSec != 0 {
		i = encodeVarintIcqoracle(dAtA, i, uint64(m.UpdateIntervalSec))
		i--
		dAtA[i] = 0x18
	}
	if len(m.OsmosisConnectionId) > 0 {
		i -= len(m.OsmosisConnectionId)
		copy(dAtA[i:], m.OsmosisConnectionId)
		i = encodeVarintIcqoracle(dAtA, i, uint64(len(m.OsmosisConnectionId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.OsmosisChainId) > 0 {
		i -= len(m.OsmosisChainId)
		copy(dAtA[i:], m.OsmosisChainId)
		i = encodeVarintIcqoracle(dAtA, i, uint64(len(m.OsmosisChainId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintIcqoracle(dAtA []byte, offset int, v uint64) int {
	offset -= sovIcqoracle(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *TokenPrice) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.BaseDenom)
	if l > 0 {
		n += 1 + l + sovIcqoracle(uint64(l))
	}
	l = len(m.QuoteDenom)
	if l > 0 {
		n += 1 + l + sovIcqoracle(uint64(l))
	}
	l = m.Price.Size()
	n += 1 + l + sovIcqoracle(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.UpdatedAt)
	n += 1 + l + sovIcqoracle(uint64(l))
	if m.QueryInProgress {
		n += 2
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OsmosisChainId)
	if l > 0 {
		n += 1 + l + sovIcqoracle(uint64(l))
	}
	l = len(m.OsmosisConnectionId)
	if l > 0 {
		n += 1 + l + sovIcqoracle(uint64(l))
	}
	if m.UpdateIntervalSec != 0 {
		n += 1 + sovIcqoracle(uint64(m.UpdateIntervalSec))
	}
	if m.TimeoutSec != 0 {
		n += 1 + sovIcqoracle(uint64(m.TimeoutSec))
	}
	return n
}

func sovIcqoracle(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozIcqoracle(x uint64) (n int) {
	return sovIcqoracle(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *TokenPrice) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIcqoracle
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TokenPrice: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TokenPrice: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIcqoracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIcqoracle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIcqoracle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BaseDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QuoteDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIcqoracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIcqoracle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIcqoracle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.QuoteDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIcqoracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIcqoracle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIcqoracle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Price.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIcqoracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthIcqoracle
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthIcqoracle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.UpdatedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field QueryInProgress", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIcqoracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.QueryInProgress = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipIcqoracle(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIcqoracle
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIcqoracle
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OsmosisChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIcqoracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIcqoracle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIcqoracle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OsmosisChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OsmosisConnectionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIcqoracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIcqoracle
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIcqoracle
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OsmosisConnectionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdateIntervalSec", wireType)
			}
			m.UpdateIntervalSec = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIcqoracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdateIntervalSec |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeoutSec", wireType)
			}
			m.TimeoutSec = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIcqoracle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimeoutSec |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipIcqoracle(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIcqoracle
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipIcqoracle(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowIcqoracle
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIcqoracle
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIcqoracle
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthIcqoracle
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupIcqoracle
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthIcqoracle
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthIcqoracle        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowIcqoracle          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupIcqoracle = fmt.Errorf("proto: unexpected end of group")
)
