// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: stakeibc/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc8fd2cb3c1d11f2, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc8fd2cb3c1d11f2, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetValidatorRequest struct {
}

func (m *QueryGetValidatorRequest) Reset()         { *m = QueryGetValidatorRequest{} }
func (m *QueryGetValidatorRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetValidatorRequest) ProtoMessage()    {}
func (*QueryGetValidatorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc8fd2cb3c1d11f2, []int{2}
}
func (m *QueryGetValidatorRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetValidatorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetValidatorRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetValidatorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetValidatorRequest.Merge(m, src)
}
func (m *QueryGetValidatorRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetValidatorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetValidatorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetValidatorRequest proto.InternalMessageInfo

type QueryGetValidatorResponse struct {
	Validator Validator `protobuf:"bytes,1,opt,name=Validator,proto3" json:"Validator"`
}

func (m *QueryGetValidatorResponse) Reset()         { *m = QueryGetValidatorResponse{} }
func (m *QueryGetValidatorResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetValidatorResponse) ProtoMessage()    {}
func (*QueryGetValidatorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc8fd2cb3c1d11f2, []int{3}
}
func (m *QueryGetValidatorResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetValidatorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetValidatorResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetValidatorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetValidatorResponse.Merge(m, src)
}
func (m *QueryGetValidatorResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetValidatorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetValidatorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetValidatorResponse proto.InternalMessageInfo

func (m *QueryGetValidatorResponse) GetValidator() Validator {
	if m != nil {
		return m.Validator
	}
	return Validator{}
}

type QueryGetDelegationRequest struct {
}

func (m *QueryGetDelegationRequest) Reset()         { *m = QueryGetDelegationRequest{} }
func (m *QueryGetDelegationRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetDelegationRequest) ProtoMessage()    {}
func (*QueryGetDelegationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc8fd2cb3c1d11f2, []int{4}
}
func (m *QueryGetDelegationRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDelegationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDelegationRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDelegationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDelegationRequest.Merge(m, src)
}
func (m *QueryGetDelegationRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDelegationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDelegationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDelegationRequest proto.InternalMessageInfo

type QueryGetDelegationResponse struct {
	Delegation Delegation `protobuf:"bytes,1,opt,name=Delegation,proto3" json:"Delegation"`
}

func (m *QueryGetDelegationResponse) Reset()         { *m = QueryGetDelegationResponse{} }
func (m *QueryGetDelegationResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetDelegationResponse) ProtoMessage()    {}
func (*QueryGetDelegationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc8fd2cb3c1d11f2, []int{5}
}
func (m *QueryGetDelegationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDelegationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDelegationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDelegationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDelegationResponse.Merge(m, src)
}
func (m *QueryGetDelegationResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDelegationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDelegationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDelegationResponse proto.InternalMessageInfo

func (m *QueryGetDelegationResponse) GetDelegation() Delegation {
	if m != nil {
		return m.Delegation
	}
	return Delegation{}
}

type QueryGetMinValidatorRequirementsRequest struct {
}

func (m *QueryGetMinValidatorRequirementsRequest) Reset() {
	*m = QueryGetMinValidatorRequirementsRequest{}
}
func (m *QueryGetMinValidatorRequirementsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetMinValidatorRequirementsRequest) ProtoMessage()    {}
func (*QueryGetMinValidatorRequirementsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc8fd2cb3c1d11f2, []int{6}
}
func (m *QueryGetMinValidatorRequirementsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetMinValidatorRequirementsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetMinValidatorRequirementsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetMinValidatorRequirementsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetMinValidatorRequirementsRequest.Merge(m, src)
}
func (m *QueryGetMinValidatorRequirementsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetMinValidatorRequirementsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetMinValidatorRequirementsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetMinValidatorRequirementsRequest proto.InternalMessageInfo

type QueryGetMinValidatorRequirementsResponse struct {
	MinValidatorRequirements MinValidatorRequirements `protobuf:"bytes,1,opt,name=MinValidatorRequirements,proto3" json:"MinValidatorRequirements"`
}

func (m *QueryGetMinValidatorRequirementsResponse) Reset() {
	*m = QueryGetMinValidatorRequirementsResponse{}
}
func (m *QueryGetMinValidatorRequirementsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetMinValidatorRequirementsResponse) ProtoMessage()    {}
func (*QueryGetMinValidatorRequirementsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc8fd2cb3c1d11f2, []int{7}
}
func (m *QueryGetMinValidatorRequirementsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetMinValidatorRequirementsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetMinValidatorRequirementsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetMinValidatorRequirementsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetMinValidatorRequirementsResponse.Merge(m, src)
}
func (m *QueryGetMinValidatorRequirementsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetMinValidatorRequirementsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetMinValidatorRequirementsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetMinValidatorRequirementsResponse proto.InternalMessageInfo

func (m *QueryGetMinValidatorRequirementsResponse) GetMinValidatorRequirements() MinValidatorRequirements {
	if m != nil {
		return m.MinValidatorRequirements
	}
	return MinValidatorRequirements{}
}

type QueryGetICAAccountRequest struct {
}

func (m *QueryGetICAAccountRequest) Reset()         { *m = QueryGetICAAccountRequest{} }
func (m *QueryGetICAAccountRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetICAAccountRequest) ProtoMessage()    {}
func (*QueryGetICAAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc8fd2cb3c1d11f2, []int{8}
}
func (m *QueryGetICAAccountRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetICAAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetICAAccountRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetICAAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetICAAccountRequest.Merge(m, src)
}
func (m *QueryGetICAAccountRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetICAAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetICAAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetICAAccountRequest proto.InternalMessageInfo

type QueryGetICAAccountResponse struct {
	ICAAccount ICAAccount `protobuf:"bytes,1,opt,name=ICAAccount,proto3" json:"ICAAccount"`
}

func (m *QueryGetICAAccountResponse) Reset()         { *m = QueryGetICAAccountResponse{} }
func (m *QueryGetICAAccountResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetICAAccountResponse) ProtoMessage()    {}
func (*QueryGetICAAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc8fd2cb3c1d11f2, []int{9}
}
func (m *QueryGetICAAccountResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetICAAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetICAAccountResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetICAAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetICAAccountResponse.Merge(m, src)
}
func (m *QueryGetICAAccountResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetICAAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetICAAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetICAAccountResponse proto.InternalMessageInfo

func (m *QueryGetICAAccountResponse) GetICAAccount() ICAAccount {
	if m != nil {
		return m.ICAAccount
	}
	return ICAAccount{}
}

type QueryGetHostZoneRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetHostZoneRequest) Reset()         { *m = QueryGetHostZoneRequest{} }
func (m *QueryGetHostZoneRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetHostZoneRequest) ProtoMessage()    {}
func (*QueryGetHostZoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc8fd2cb3c1d11f2, []int{10}
}
func (m *QueryGetHostZoneRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetHostZoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetHostZoneRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetHostZoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetHostZoneRequest.Merge(m, src)
}
func (m *QueryGetHostZoneRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetHostZoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetHostZoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetHostZoneRequest proto.InternalMessageInfo

func (m *QueryGetHostZoneRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetHostZoneResponse struct {
	HostZone HostZone `protobuf:"bytes,1,opt,name=HostZone,proto3" json:"HostZone"`
}

func (m *QueryGetHostZoneResponse) Reset()         { *m = QueryGetHostZoneResponse{} }
func (m *QueryGetHostZoneResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetHostZoneResponse) ProtoMessage()    {}
func (*QueryGetHostZoneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc8fd2cb3c1d11f2, []int{11}
}
func (m *QueryGetHostZoneResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetHostZoneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetHostZoneResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetHostZoneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetHostZoneResponse.Merge(m, src)
}
func (m *QueryGetHostZoneResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetHostZoneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetHostZoneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetHostZoneResponse proto.InternalMessageInfo

func (m *QueryGetHostZoneResponse) GetHostZone() HostZone {
	if m != nil {
		return m.HostZone
	}
	return HostZone{}
}

type QueryAllHostZoneRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllHostZoneRequest) Reset()         { *m = QueryAllHostZoneRequest{} }
func (m *QueryAllHostZoneRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllHostZoneRequest) ProtoMessage()    {}
func (*QueryAllHostZoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc8fd2cb3c1d11f2, []int{12}
}
func (m *QueryAllHostZoneRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllHostZoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllHostZoneRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllHostZoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllHostZoneRequest.Merge(m, src)
}
func (m *QueryAllHostZoneRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllHostZoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllHostZoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllHostZoneRequest proto.InternalMessageInfo

func (m *QueryAllHostZoneRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllHostZoneResponse struct {
	HostZone   []HostZone          `protobuf:"bytes,1,rep,name=HostZone,proto3" json:"HostZone"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllHostZoneResponse) Reset()         { *m = QueryAllHostZoneResponse{} }
func (m *QueryAllHostZoneResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllHostZoneResponse) ProtoMessage()    {}
func (*QueryAllHostZoneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc8fd2cb3c1d11f2, []int{13}
}
func (m *QueryAllHostZoneResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllHostZoneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllHostZoneResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllHostZoneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllHostZoneResponse.Merge(m, src)
}
func (m *QueryAllHostZoneResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllHostZoneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllHostZoneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllHostZoneResponse proto.InternalMessageInfo

func (m *QueryAllHostZoneResponse) GetHostZone() []HostZone {
	if m != nil {
		return m.HostZone
	}
	return nil
}

func (m *QueryAllHostZoneResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "Stridelabs.stride.stakeibc.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "Stridelabs.stride.stakeibc.QueryParamsResponse")
	proto.RegisterType((*QueryGetValidatorRequest)(nil), "Stridelabs.stride.stakeibc.QueryGetValidatorRequest")
	proto.RegisterType((*QueryGetValidatorResponse)(nil), "Stridelabs.stride.stakeibc.QueryGetValidatorResponse")
	proto.RegisterType((*QueryGetDelegationRequest)(nil), "Stridelabs.stride.stakeibc.QueryGetDelegationRequest")
	proto.RegisterType((*QueryGetDelegationResponse)(nil), "Stridelabs.stride.stakeibc.QueryGetDelegationResponse")
	proto.RegisterType((*QueryGetMinValidatorRequirementsRequest)(nil), "Stridelabs.stride.stakeibc.QueryGetMinValidatorRequirementsRequest")
	proto.RegisterType((*QueryGetMinValidatorRequirementsResponse)(nil), "Stridelabs.stride.stakeibc.QueryGetMinValidatorRequirementsResponse")
	proto.RegisterType((*QueryGetICAAccountRequest)(nil), "Stridelabs.stride.stakeibc.QueryGetICAAccountRequest")
	proto.RegisterType((*QueryGetICAAccountResponse)(nil), "Stridelabs.stride.stakeibc.QueryGetICAAccountResponse")
	proto.RegisterType((*QueryGetHostZoneRequest)(nil), "Stridelabs.stride.stakeibc.QueryGetHostZoneRequest")
	proto.RegisterType((*QueryGetHostZoneResponse)(nil), "Stridelabs.stride.stakeibc.QueryGetHostZoneResponse")
	proto.RegisterType((*QueryAllHostZoneRequest)(nil), "Stridelabs.stride.stakeibc.QueryAllHostZoneRequest")
	proto.RegisterType((*QueryAllHostZoneResponse)(nil), "Stridelabs.stride.stakeibc.QueryAllHostZoneResponse")
}

func init() { proto.RegisterFile("stakeibc/query.proto", fileDescriptor_cc8fd2cb3c1d11f2) }

var fileDescriptor_cc8fd2cb3c1d11f2 = []byte{
	// 790 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x96, 0xcb, 0x6e, 0xd3, 0x4c,
	0x14, 0xc7, 0xe3, 0x7c, 0xfd, 0x2a, 0x3a, 0x95, 0x58, 0x0c, 0x45, 0xa4, 0x06, 0x05, 0x64, 0x95,
	0x36, 0x29, 0xaa, 0x4d, 0x2f, 0x80, 0x58, 0x41, 0xda, 0xaa, 0x17, 0x09, 0xa4, 0x12, 0x24, 0x90,
	0xba, 0x89, 0x26, 0xc9, 0xe0, 0x0e, 0x38, 0x9e, 0xd4, 0x9e, 0x54, 0x14, 0xc4, 0x86, 0x27, 0x40,
	0x42, 0xbc, 0x00, 0x2b, 0xc4, 0xe5, 0x3d, 0xba, 0xac, 0xc4, 0x86, 0x15, 0x42, 0x2d, 0x62, 0xc1,
	0x53, 0xa0, 0x8c, 0xe7, 0xe2, 0x34, 0x8e, 0xe3, 0xc2, 0xce, 0x9a, 0x73, 0xfe, 0xe7, 0xfc, 0xce,
	0xb1, 0xfd, 0xb7, 0xc1, 0x44, 0xc8, 0xd0, 0x33, 0x4c, 0xea, 0x0d, 0x67, 0xb7, 0x83, 0x83, 0x7d,
	0xbb, 0x1d, 0x50, 0x46, 0xa1, 0xf9, 0x90, 0x05, 0xa4, 0x89, 0x3d, 0x54, 0x0f, 0xed, 0x90, 0x5f,
	0xda, 0x32, 0xcf, 0x9c, 0x70, 0xa9, 0x4b, 0x79, 0x9a, 0xd3, 0xbd, 0x8a, 0x14, 0xe6, 0x25, 0x97,
	0x52, 0xd7, 0xc3, 0x0e, 0x6a, 0x13, 0x07, 0xf9, 0x3e, 0x65, 0x88, 0x11, 0xea, 0x87, 0x22, 0x3a,
	0xdb, 0xa0, 0x61, 0x8b, 0x86, 0x4e, 0x1d, 0x85, 0x38, 0x6a, 0xe4, 0xec, 0xcd, 0xd7, 0x31, 0x43,
	0xf3, 0x4e, 0x1b, 0xb9, 0xc4, 0xe7, 0xc9, 0x22, 0xf7, 0xbc, 0x22, 0x6a, 0xa3, 0x00, 0xb5, 0x64,
	0x89, 0x82, 0x3a, 0xde, 0x43, 0x1e, 0x69, 0x22, 0x46, 0x03, 0x11, 0x99, 0x54, 0x91, 0x26, 0xf6,
	0xb0, 0x1b, 0xaf, 0x55, 0x56, 0xa1, 0x16, 0xf1, 0x6b, 0x4a, 0x58, 0x0b, 0xf0, 0x6e, 0x87, 0x04,
	0xb8, 0x85, 0x7d, 0x26, 0xeb, 0x9b, 0x2a, 0x95, 0x34, 0x50, 0x0d, 0x35, 0x1a, 0xb4, 0xe3, 0xb3,
	0xbe, 0xde, 0x3b, 0x34, 0x64, 0xb5, 0x17, 0xd4, 0xc7, 0x51, 0xc4, 0x9a, 0x00, 0xf0, 0x41, 0x77,
	0x9c, 0x2d, 0x8e, 0x5a, 0xc5, 0xbb, 0x1d, 0x1c, 0x32, 0xeb, 0x31, 0x38, 0xd7, 0x73, 0x1a, 0xb6,
	0xa9, 0x1f, 0x62, 0x78, 0x17, 0x8c, 0x46, 0x23, 0x15, 0x8c, 0x2b, 0x46, 0x69, 0x7c, 0xc1, 0xb2,
	0x07, 0xaf, 0xd9, 0x8e, 0xb4, 0xcb, 0x23, 0x07, 0xdf, 0x2f, 0xe7, 0xaa, 0x42, 0x67, 0x99, 0xa0,
	0xc0, 0x0b, 0xaf, 0x63, 0xf6, 0x48, 0x0e, 0x23, 0x9b, 0x3e, 0x01, 0x93, 0x09, 0x31, 0xd1, 0x7a,
	0x13, 0x8c, 0xa9, 0x43, 0xd1, 0xfd, 0x6a, 0x5a, 0x77, 0x95, 0x2c, 0x00, 0xb4, 0xda, 0xba, 0xa8,
	0xfb, 0xac, 0xaa, 0x7d, 0x4b, 0x88, 0xa7, 0xc0, 0x4c, 0x0a, 0x0a, 0x8a, 0x7b, 0x00, 0xe8, 0x53,
	0x81, 0x31, 0x9d, 0x86, 0xa1, 0xb3, 0x05, 0x47, 0x4c, 0x6f, 0x95, 0xc1, 0x8c, 0xec, 0x75, 0x9f,
	0xf8, 0x3d, 0xfb, 0x90, 0xf7, 0x56, 0x62, 0xbd, 0x37, 0x40, 0x69, 0x78, 0xae, 0xa0, 0xdc, 0x03,
	0x85, 0x41, 0x39, 0x82, 0x79, 0x29, 0x8d, 0x79, 0x90, 0x56, 0x4c, 0x30, 0xb0, 0x76, 0x7c, 0xb1,
	0x9b, 0x2b, 0x95, 0x4a, 0xf4, 0x04, 0x26, 0x2c, 0x36, 0x1e, 0xd4, 0x8b, 0xd5, 0xa7, 0x59, 0x16,
	0xab, 0xb3, 0xe5, 0x62, 0xf5, 0x89, 0x55, 0x06, 0x17, 0x64, 0xaf, 0x0d, 0x1a, 0xb2, 0x6d, 0xea,
	0x63, 0x81, 0x01, 0xcf, 0x82, 0x3c, 0x69, 0xf2, 0x06, 0x23, 0xd5, 0x3c, 0x69, 0x5a, 0x75, 0xfd,
	0x40, 0xea, 0x54, 0x01, 0xb5, 0x06, 0xce, 0xc8, 0x33, 0x81, 0x34, 0x95, 0x86, 0x24, 0x73, 0x05,
	0x90, 0xd2, 0x5a, 0x48, 0xe0, 0x54, 0x3c, 0xef, 0x24, 0xce, 0x1a, 0x00, 0xda, 0x3f, 0xd4, 0xdc,
	0x91, 0xd9, 0xd8, 0x5d, 0xb3, 0xb1, 0x23, 0x57, 0x13, 0x66, 0x63, 0x6f, 0x21, 0x57, 0x6a, 0xab,
	0x31, 0xa5, 0xf5, 0xc9, 0x10, 0x73, 0xf4, 0xf4, 0x48, 0x9c, 0xe3, 0xbf, 0xbf, 0x9d, 0x03, 0xae,
	0xf7, 0xc0, 0xe6, 0x39, 0xec, 0xcc, 0x50, 0xd8, 0x08, 0x22, 0x4e, 0xbb, 0xf0, 0x7b, 0x0c, 0xfc,
	0xcf, 0x69, 0xe1, 0x3b, 0x03, 0x8c, 0x46, 0x46, 0x01, 0xed, 0x34, 0xa6, 0x7e, 0x8f, 0x32, 0x9d,
	0xcc, 0xf9, 0x11, 0x81, 0x35, 0xfb, 0xfa, 0xeb, 0xcf, 0xb7, 0xf9, 0x29, 0x68, 0x39, 0x5a, 0xe8,
	0x44, 0x42, 0xe7, 0x84, 0x65, 0xc3, 0x0f, 0x46, 0xcc, 0x6f, 0xe0, 0xd2, 0xd0, 0x56, 0x09, 0x7e,
	0x66, 0xde, 0x38, 0xa5, 0x4a, 0x60, 0xda, 0x1c, 0xb3, 0x04, 0xa7, 0x05, 0xe6, 0x5c, 0x22, 0xa7,
	0xfa, 0x14, 0xc0, 0xcf, 0x46, 0xdc, 0x94, 0x60, 0xa6, 0xae, 0x7d, 0xbe, 0x67, 0xde, 0x3c, 0xad,
	0x4c, 0xd0, 0x3a, 0x9c, 0xb6, 0x0c, 0x67, 0x52, 0x69, 0xf5, 0x77, 0x0d, 0xfe, 0x32, 0x06, 0xbb,
	0x13, 0x5c, 0xc9, 0x42, 0x31, 0xc4, 0x2b, 0xcd, 0xd5, 0x7f, 0x2b, 0x22, 0x06, 0xbb, 0xc3, 0x07,
	0xbb, 0x0d, 0x6f, 0xa5, 0x0e, 0x36, 0xf8, 0xab, 0x0c, 0xbf, 0x18, 0x71, 0x4f, 0xcb, 0x76, 0x5f,
	0xfa, 0x6c, 0x33, 0xdb, 0x7d, 0xe9, 0x37, 0x54, 0xeb, 0x3a, 0xc7, 0x9f, 0x85, 0xa5, 0x54, 0xfc,
	0xd8, 0x9f, 0x02, 0xfc, 0x68, 0x68, 0x9b, 0x80, 0x8b, 0x59, 0xda, 0x9e, 0x30, 0x33, 0x73, 0xe9,
	0x74, 0x22, 0x41, 0xba, 0xc8, 0x49, 0xe7, 0xe0, 0xb5, 0x54, 0x52, 0xf5, 0xdf, 0xe2, 0xbc, 0x24,
	0xcd, 0x57, 0xdd, 0xf7, 0x73, 0x5c, 0x56, 0xaa, 0x78, 0x5e, 0x06, 0xde, 0x7e, 0xf3, 0xcd, 0xc0,
	0x9b, 0xe0, 0xa6, 0x19, 0xdf, 0x4f, 0xc5, 0xbb, 0xbc, 0x71, 0x70, 0x54, 0x34, 0x0e, 0x8f, 0x8a,
	0xc6, 0x8f, 0xa3, 0xa2, 0xf1, 0xe6, 0xb8, 0x98, 0x3b, 0x3c, 0x2e, 0xe6, 0xbe, 0x1d, 0x17, 0x73,
	0xdb, 0xb6, 0x4b, 0xd8, 0x4e, 0xa7, 0x6e, 0x37, 0x68, 0x2b, 0xa9, 0xd6, 0x73, 0x5d, 0x8d, 0xed,
	0xb7, 0x71, 0x58, 0x1f, 0xe5, 0xbf, 0x6c, 0x8b, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x55, 0x0a,
	0x88, 0x0c, 0xf3, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a Validator by index.
	Validator(ctx context.Context, in *QueryGetValidatorRequest, opts ...grpc.CallOption) (*QueryGetValidatorResponse, error)
	// Queries a Delegation by index.
	Delegation(ctx context.Context, in *QueryGetDelegationRequest, opts ...grpc.CallOption) (*QueryGetDelegationResponse, error)
	// Queries a MinValidatorRequirements by index.
	MinValidatorRequirements(ctx context.Context, in *QueryGetMinValidatorRequirementsRequest, opts ...grpc.CallOption) (*QueryGetMinValidatorRequirementsResponse, error)
	// Queries a ICAAccount by index.
	ICAAccount(ctx context.Context, in *QueryGetICAAccountRequest, opts ...grpc.CallOption) (*QueryGetICAAccountResponse, error)
	// Queries a HostZone by id.
	HostZone(ctx context.Context, in *QueryGetHostZoneRequest, opts ...grpc.CallOption) (*QueryGetHostZoneResponse, error)
	// Queries a list of HostZone items.
	HostZoneAll(ctx context.Context, in *QueryAllHostZoneRequest, opts ...grpc.CallOption) (*QueryAllHostZoneResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/Stridelabs.stride.stakeibc.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Validator(ctx context.Context, in *QueryGetValidatorRequest, opts ...grpc.CallOption) (*QueryGetValidatorResponse, error) {
	out := new(QueryGetValidatorResponse)
	err := c.cc.Invoke(ctx, "/Stridelabs.stride.stakeibc.Query/Validator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Delegation(ctx context.Context, in *QueryGetDelegationRequest, opts ...grpc.CallOption) (*QueryGetDelegationResponse, error) {
	out := new(QueryGetDelegationResponse)
	err := c.cc.Invoke(ctx, "/Stridelabs.stride.stakeibc.Query/Delegation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) MinValidatorRequirements(ctx context.Context, in *QueryGetMinValidatorRequirementsRequest, opts ...grpc.CallOption) (*QueryGetMinValidatorRequirementsResponse, error) {
	out := new(QueryGetMinValidatorRequirementsResponse)
	err := c.cc.Invoke(ctx, "/Stridelabs.stride.stakeibc.Query/MinValidatorRequirements", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ICAAccount(ctx context.Context, in *QueryGetICAAccountRequest, opts ...grpc.CallOption) (*QueryGetICAAccountResponse, error) {
	out := new(QueryGetICAAccountResponse)
	err := c.cc.Invoke(ctx, "/Stridelabs.stride.stakeibc.Query/ICAAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) HostZone(ctx context.Context, in *QueryGetHostZoneRequest, opts ...grpc.CallOption) (*QueryGetHostZoneResponse, error) {
	out := new(QueryGetHostZoneResponse)
	err := c.cc.Invoke(ctx, "/Stridelabs.stride.stakeibc.Query/HostZone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) HostZoneAll(ctx context.Context, in *QueryAllHostZoneRequest, opts ...grpc.CallOption) (*QueryAllHostZoneResponse, error) {
	out := new(QueryAllHostZoneResponse)
	err := c.cc.Invoke(ctx, "/Stridelabs.stride.stakeibc.Query/HostZoneAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a Validator by index.
	Validator(context.Context, *QueryGetValidatorRequest) (*QueryGetValidatorResponse, error)
	// Queries a Delegation by index.
	Delegation(context.Context, *QueryGetDelegationRequest) (*QueryGetDelegationResponse, error)
	// Queries a MinValidatorRequirements by index.
	MinValidatorRequirements(context.Context, *QueryGetMinValidatorRequirementsRequest) (*QueryGetMinValidatorRequirementsResponse, error)
	// Queries a ICAAccount by index.
	ICAAccount(context.Context, *QueryGetICAAccountRequest) (*QueryGetICAAccountResponse, error)
	// Queries a HostZone by id.
	HostZone(context.Context, *QueryGetHostZoneRequest) (*QueryGetHostZoneResponse, error)
	// Queries a list of HostZone items.
	HostZoneAll(context.Context, *QueryAllHostZoneRequest) (*QueryAllHostZoneResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) Validator(ctx context.Context, req *QueryGetValidatorRequest) (*QueryGetValidatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Validator not implemented")
}
func (*UnimplementedQueryServer) Delegation(ctx context.Context, req *QueryGetDelegationRequest) (*QueryGetDelegationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delegation not implemented")
}
func (*UnimplementedQueryServer) MinValidatorRequirements(ctx context.Context, req *QueryGetMinValidatorRequirementsRequest) (*QueryGetMinValidatorRequirementsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MinValidatorRequirements not implemented")
}
func (*UnimplementedQueryServer) ICAAccount(ctx context.Context, req *QueryGetICAAccountRequest) (*QueryGetICAAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ICAAccount not implemented")
}
func (*UnimplementedQueryServer) HostZone(ctx context.Context, req *QueryGetHostZoneRequest) (*QueryGetHostZoneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HostZone not implemented")
}
func (*UnimplementedQueryServer) HostZoneAll(ctx context.Context, req *QueryAllHostZoneRequest) (*QueryAllHostZoneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HostZoneAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Stridelabs.stride.stakeibc.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Validator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetValidatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Validator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Stridelabs.stride.stakeibc.Query/Validator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Validator(ctx, req.(*QueryGetValidatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Delegation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetDelegationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Delegation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Stridelabs.stride.stakeibc.Query/Delegation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Delegation(ctx, req.(*QueryGetDelegationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_MinValidatorRequirements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetMinValidatorRequirementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).MinValidatorRequirements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Stridelabs.stride.stakeibc.Query/MinValidatorRequirements",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).MinValidatorRequirements(ctx, req.(*QueryGetMinValidatorRequirementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ICAAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetICAAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ICAAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Stridelabs.stride.stakeibc.Query/ICAAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ICAAccount(ctx, req.(*QueryGetICAAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_HostZone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetHostZoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).HostZone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Stridelabs.stride.stakeibc.Query/HostZone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).HostZone(ctx, req.(*QueryGetHostZoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_HostZoneAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllHostZoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).HostZoneAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Stridelabs.stride.stakeibc.Query/HostZoneAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).HostZoneAll(ctx, req.(*QueryAllHostZoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Stridelabs.stride.stakeibc.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Validator",
			Handler:    _Query_Validator_Handler,
		},
		{
			MethodName: "Delegation",
			Handler:    _Query_Delegation_Handler,
		},
		{
			MethodName: "MinValidatorRequirements",
			Handler:    _Query_MinValidatorRequirements_Handler,
		},
		{
			MethodName: "ICAAccount",
			Handler:    _Query_ICAAccount_Handler,
		},
		{
			MethodName: "HostZone",
			Handler:    _Query_HostZone_Handler,
		},
		{
			MethodName: "HostZoneAll",
			Handler:    _Query_HostZoneAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stakeibc/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetValidatorRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetValidatorRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetValidatorRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetValidatorResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetValidatorResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetValidatorResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Validator.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetDelegationRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDelegationRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDelegationRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetDelegationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDelegationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDelegationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Delegation.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetMinValidatorRequirementsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetMinValidatorRequirementsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetMinValidatorRequirementsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetMinValidatorRequirementsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetMinValidatorRequirementsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetMinValidatorRequirementsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.MinValidatorRequirements.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetICAAccountRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetICAAccountRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetICAAccountRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetICAAccountResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetICAAccountResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetICAAccountResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.ICAAccount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetHostZoneRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetHostZoneRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetHostZoneRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetHostZoneResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetHostZoneResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetHostZoneResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.HostZone.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllHostZoneRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllHostZoneRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllHostZoneRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllHostZoneResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllHostZoneResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllHostZoneResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.HostZone) > 0 {
		for iNdEx := len(m.HostZone) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.HostZone[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetValidatorRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetValidatorResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Validator.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetDelegationRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetDelegationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Delegation.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetMinValidatorRequirementsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetMinValidatorRequirementsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.MinValidatorRequirements.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetICAAccountRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetICAAccountResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ICAAccount.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetHostZoneRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetHostZoneResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.HostZone.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllHostZoneRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllHostZoneResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.HostZone) > 0 {
		for _, e := range m.HostZone {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetValidatorRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetValidatorRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetValidatorRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetValidatorResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetValidatorResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetValidatorResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validator", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Validator.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetDelegationRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDelegationRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDelegationRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetDelegationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDelegationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDelegationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Delegation", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Delegation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetMinValidatorRequirementsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetMinValidatorRequirementsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetMinValidatorRequirementsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetMinValidatorRequirementsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetMinValidatorRequirementsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetMinValidatorRequirementsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinValidatorRequirements", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinValidatorRequirements.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetICAAccountRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetICAAccountRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetICAAccountRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetICAAccountResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetICAAccountResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetICAAccountResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ICAAccount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ICAAccount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetHostZoneRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetHostZoneRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetHostZoneRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetHostZoneResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetHostZoneResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetHostZoneResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HostZone", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.HostZone.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllHostZoneRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllHostZoneRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllHostZoneRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllHostZoneResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllHostZoneResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllHostZoneResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HostZone", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HostZone = append(m.HostZone, HostZone{})
			if err := m.HostZone[len(m.HostZone)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
