[mode]
[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = true

[mode.channels]
enabled = true

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true

[rest]
enabled = true
host = '0.0.0.0'
port = 3000

[telemetry]
enabled = true
host = '0.0.0.0'
port = 3001

[[chains]]
id = 'internal'
rpc_addr = 'http://stride_1.internal.stridelabs.co:26657'
grpc_addr = 'http://stride_1.internal.stridelabs.co:9090'
websocket_addr = 'ws://stride_1.internal.stridelabs.co:26657/websocket'
rpc_timeout = '10s'
account_prefix = 'stride'
key_name = 'testkey'
store_prefix = 'ibc'
default_gas = 100000
max_gas = 5000000
gas_price = { price = 0.000000, denom = 'ustrd' }
gas_adjustment = 0.1
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
max_block_time = '10s'
trusting_period = '150s'
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'cosmos' }

[[chains]]
id = 'GAIA_internal'
rpc_addr = 'http://gaia.internal.stridelabs.co:26657'
grpc_addr = 'http://gaia.internal.stridelabs.co:9090'
websocket_addr = 'ws://gaia.internal.stridelabs.co:26657/websocket'
rpc_timeout = '10s'
account_prefix = 'cosmos'
key_name = 'testkey'
store_prefix = 'ibc'
default_gas = 100000
max_gas = 3000000
gas_price = { price = 0.000, denom = 'uatom' }
gas_adjustment = 0.1
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
max_block_time = '10s'
trusting_period = '150s'
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'cosmos' }