[global]
log_level = 'debug'

[mode]
[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = true

[mode.channels]
enabled = true

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true

[rest]
enabled = false
host = '0.0.0.0'
port = 3000

[telemetry]
enabled = false
host = '127.0.0.1'
port = 3001

[[chains]]
id = 'stride-test-1'
rpc_addr = 'http://stride-validator.integration.svc:26657'
grpc_addr = 'http://stride-validator.integration.svc:9090'
event_source = { mode = 'push', url = 'ws://stride-validator.integration.svc:26657/websocket', batch_delay = '500ms' }
rpc_timeout = '10s'
account_prefix = 'stride'
key_name = 'stride'
store_prefix = 'ibc'
# TODO: investigate why this has to be set so high
gas_price = { price = 1, denom = 'ustrd' }
gas_multiplier = 1.3
clock_drift = '10s'
max_block_time = '10s'
address_type = { derivation = 'cosmos' }
memo_prefix = 'stride-tests'

[[chains]]
id = 'cosmoshub-test-1'
rpc_addr = 'http://cosmoshub-validator.integration.svc:26657'
grpc_addr = 'http://cosmoshub-validator.integration.svc:9090'
event_source = { mode = 'push', url = 'ws://cosmoshub-validator.integration.svc:26657/websocket', batch_delay = '500ms' }
rpc_timeout = '10s'
account_prefix = 'cosmos'
key_name = 'cosmoshub'
store_prefix = 'ibc'
# TODO: investigate why this has to be set so high
gas_price = { price = 1, denom = 'uatom' }
gas_multiplier = 1.3
clock_drift = '10s'
max_block_time = '10s'
address_type = { derivation = 'cosmos' }
memo_prefix = 'stride-tests'
