global:
  api-listen-addr: :5183
  timeout: 10s
  memo: stride-tests
  light-cache-size: 20
chains:
  stride:
    type: cosmos
    value:
      key: stride
      chain-id: stride-test-1
      rpc-addr: http://stride-validator.integration.svc:26657
      account-prefix: stride
      keyring-backend: test
      gas-adjustment: 1.2
      gas-prices: 0.0005ustrd
      coin-type: 118
      debug: false
      timeout: 20s
      output-format: json
      sign-mode: direct
      min-loop-duration: 2s
  cosmoshub:
    type: cosmos
    value:
      key: cosmoshub
      chain-id: cosmoshub-test-1
      rpc-addr: http://cosmoshub-validator.integration.svc:26657
      account-prefix: cosmos
      keyring-backend: test
      gas-adjustment: 1.3
      gas-prices: 0.01uatom
      coin-type: 118
      min-loop-duration: 5s
      debug: false
      timeout: 20s
      output-format: json
      sign-mode: direct
paths:
  stride-cosmoshub:
    src:
      chain-id: stride-test-1
    dst:
      chain-id: cosmoshub-test-1