# syntax = docker/dockerfile:1
FROM golang:1.19-alpine3.15 AS builder

WORKDIR /opt/

ENV COMMIT_HASH=25e2a8641e757eeb23e7730cfd60af32b8b6dd6f

RUN apk add --update git make gcc linux-headers libc-dev eudev-dev
RUN git clone https://github.com/cosmos/relayer.git \
    && cd relayer \
    && git checkout $COMMIT_HASH \
    && make install

WORKDIR /home/relayer

# Create startup script that takes a path as a parameter
RUN echo 'rly start $1 -p events' > start.sh