#!/usr/bin/env bash
sc_name=`basename "$0"`
export LOGFILE=node_log

# Bootstapconfig
node_bootstrap(){

    echo "[*] Bootstrapping node . . "
	VAL_ACC=$(hostname)
	USER_ACC=$(echo $RANDOM | md5sum | head -c 8)
	MONIKER=$VAL_ACC
    chainID=chain-$USER_ACC
	umeed init $MONIKER --chain-id $chainID 2>> $LOGFILE

	# Add Accounts
	umeed keys add $VAL_ACC --keyring-backend test >> val_acc.txt
	umeed keys add $USER_ACC --keyring-backend test >> user_acc.txt

	VALIDATOR_ADDRESS=$(umeed keys show $VAL_ACC -a --keyring-backend test)
	umeed add-genesis-account $VALIDATOR_ADDRESS 10000000000uumee 2>> $LOGFILE
	OPS_ADDRESS=$(umeed keys show $USER_ACC -a --keyring-backend test)
	umeed add-genesis-account $OPS_ADDRESS 20000000000uumee 2>> $LOGFILE

	umeed gentx $VAL_ACC 100000000uumee --chain-id $chainID --keyring-backend test 2>> $LOGFILE
	umeed collect-gentxs 2>> $LOGFILE

}

# Start the node
node_start(){

  node_bootstrap
  ipaddr=0.0.0.0
  umeed start --address="$ipaddr:26658" --api.address="tcp://$ipaddr:1317" --grpc.address="$ipaddr:9090" --p2p.laddr="$ipaddr:26656" --rpc.laddr="tcp://$ipaddr:26657" --api.enable=true --grpc-web.enable=false --api.enabled-unsafe-cors=true --log_level=info --minimum-gas-prices="0.1uumee" 
  

}

node_start
