apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cosmos-validator
  namespace: integration
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cosmos-validator
  serviceName: cosmos-validator
  template:
    metadata:
      labels:
        app: cosmos-validator
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: init
          image: gcr.io/stride-nodes/cosmos-test
          imagePullPolicy: Always
          command:
            - bash
            - "-c"
            - |
              if [[ -d $CHAIN_HOME/config ]]; then
                exit 0
              fi
              POD_INDEX=${HOSTNAME##*-}
              if [[ "$POD_INDEX" == "0" ]]; then
                bash scripts/init-chain.sh
              fi
              bash scripts/init-node.sh
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: state
              mountPath: /home/validator/.gaia
            - name: shared
              mountPath: /home/validator/shared
            - name: scripts
              mountPath: /home/validator/scripts
            - name: config
              mountPath: /home/validator/config
      containers:
        - name: cosmos-validator
          image: gcr.io/stride-nodes/cosmos-test
          imagePullPolicy: Always
          command: ["gaiad", "start"]
          lifecycle:
            postStart:
              exec:
                command: ["bash", "scripts/create-validator.sh"]
          readinessProbe:
            exec:
              command: ["bash", "scripts/readiness.sh"]
            periodSeconds: 10
          ports:
            - name: rpc
              containerPort: 26657
              protocol: TCP
            - name: peer
              containerPort: 26656
              protocol: TCP
            - name: api
              containerPort: 1317
              protocol: TCP
            - name: grpc
              containerPort: 9090
              protocol: TCP
          volumeMounts:
            - name: state
              mountPath: /home/validator/.gaia
            - name: scripts
              mountPath: /home/validator/scripts
            - name: config
              mountPath: /home/validator/config
          resources:
            limits:
              cpu: "1000m"
              memory: "2Gi"
            requests:
              cpu: "1000m"
              memory: "2Gi"
      volumes:
        - name: state
          emptyDir: {}
        - name: shared
          persistentVolumeClaim:
            claimName: cosmos-shared
        - name: scripts
          configMap:
            name: scripts
        - name: config
          configMap:
            name: config
---
apiVersion: v1
kind: Service
metadata:
  name: cosmos-validator
  namespace: integration
spec:
  clusterIP: None
  selector:
    app: cosmos-validator
  ports:
    - port: 26657
      name: rpc
      protocol: TCP
    - port: 26656
      name: peer
      protocol: TCP
    - port: 1317
      name: api
      protocol: TCP
    - port: 9090
      name: grpc
      protocol: TCP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cosmos-shared
  namespace: integration
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
