apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stride-validator
  namespace: integration
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stride-validator
  serviceName: stride-validator
  template:
    metadata:
      labels:
        app: stride-validator
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: init
          image: gcr.io/stride-nodes/stride-test
          imagePullPolicy: Always
          command:
            - bash
            - "-c"
            - |
              POD_INDEX=${HOSTNAME##*-}
              if [[ "$POD_INDEX" == "0" ]]; then
                bash scripts/init-chain.sh
              fi
              bash scripts/init-node.sh
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: state
              mountPath: /home/stride/.stride
            - name: scripts
              mountPath: /home/stride/scripts
            - name: config
              mountPath: /home/stride/config
      containers:
        - name: stride-validator
          image: gcr.io/stride-nodes/stride-test
          imagePullPolicy: Always
          command: ["strided", "start", "--reject-config-defaults"]
          lifecycle:
            postStart:
              exec:
                command: ["bash", "scripts/create-validator.sh"]
          readinessProbe:
            exec:
              command: ["bash", "scripts/readiness.sh"]
            periodSeconds: 10
          ports:
            - name: rpc
              containerPort: 26657
              protocol: TCP
            - name: peer
              containerPort: 26656
              protocol: TCP
            - name: api
              containerPort: 1317
              protocol: TCP
            - name: grpc
              containerPort: 9090
              protocol: TCP
          volumeMounts:
            - name: state
              mountPath: /home/stride/.stride
            - name: scripts
              mountPath: /home/stride/scripts
            - name: config
              mountPath: /home/stride/config
          resources:
            limits:
              cpu: "1000m"
              memory: "2Gi"
            requests:
              cpu: "1000m"
              memory: "2Gi"
      volumes:
        - name: state
          emptyDir: {}
        - name: scripts
          configMap:
            name: scripts
        - name: config
          configMap:
            name: config
---
apiVersion: v1
kind: Service
metadata:
  name: stride-validator
  namespace: integration
spec:
  clusterIP: None
  selector:
    app: stride-validator
  ports:
    - port: 26657
      name: rpc
      protocol: TCP
    - port: 26656
      name: peer
      protocol: TCP
    - port: 1317
      name: api
      protocol: TCP
    - port: 9090
      name: grpc
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stride-ingress
  namespace: integration
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "360"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "360"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "360"
spec:
  ingressClassName: nginx
  rules:
    - host: stride-api.internal.stridenet.co
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: stride-validator
                port:
                  number: 1317
            path: /(.*)
    - host: stride-rpc.internal.stridenet.co
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: stride-validator
                port:
                  number: 26657
            path: /(.*)
