[mode]
[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = true

[mode.channels]
enabled = true

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true

[rest]
enabled = true
host = '0.0.0.0'
port = 3000

[telemetry]
enabled = true
host = '0.0.0.0'
port = 3001

[[chains]]
id = 'STRIDE'
rpc_addr = 'http://stride1:26657'
grpc_addr = 'http://stride1:9090'
event_source = { mode = 'push', url = 'ws://stride1:26657/websocket', batch_delay = '500ms' }
rpc_timeout = '10s'
account_prefix = 'stride'
key_name = 'rly1'
store_prefix = 'ibc'
gas_price = { price = 0.000, denom = 'ustrd' }
gas_multiplier = 1.3
clock_drift = '10s'
max_block_time = '10s'
address_type = { derivation = 'cosmos' }
trusting_period = '119s'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'stride-dockernet'

[[chains]]
id = 'GAIA'
rpc_addr = 'http://gaia1:26657'
grpc_addr = 'http://gaia1:9090'
event_source = { mode = 'push', url = 'ws://gaia1:26657/websocket', batch_delay = '500ms' }
rpc_timeout = '10s'
account_prefix = 'cosmos'
key_name = 'rly2'
store_prefix = 'ibc'
default_gas = 100000
max_gas = 3000000
gas_price = { price = 0.000, denom = 'uatom' }
gas_multiplier = 1.3
clock_drift = '10s'
max_block_time = '10s'
address_type = { derivation = 'cosmos' }
trusting_period = '119s'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'stride-dockernet'

[[chains]]
id = 'JUNO'
rpc_addr = 'http://juno1:26657'
grpc_addr = 'http://juno1:9090'
event_source = { mode = 'push', url = 'ws://juno1:26657/websocket', batch_delay = '500ms' }
rpc_timeout = '10s'
account_prefix = 'juno'
key_name = 'rly3'
store_prefix = 'ibc'
default_gas = 100000
max_gas = 3000000
gas_price = { price = 0.000, denom = 'ujuno' }
gas_multiplier = 1.3
clock_drift = '10s'
max_block_time = '10s'
address_type = { derivation = 'cosmos' }
trusting_period = '119s'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'stride-dockernet'

[[chains]]
id = 'OSMO'
rpc_addr = 'http://osmo1:26657'
grpc_addr = 'http://osmo1:9090'
event_source = { mode = 'push', url = 'ws://osmo1:26657/websocket', batch_delay = '500ms' }
rpc_timeout = '10s'
account_prefix = 'osmo'
key_name = 'rly4'
store_prefix = 'ibc'
default_gas = 100000
max_gas = 3000000
gas_price = { price = 0.000, denom = 'uosmo' }
gas_multiplier = 1.3
clock_drift = '10s'
max_block_time = '10s'
address_type = { derivation = 'cosmos' }
trusting_period = '119s'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'stride-dockernet'

[[chains]]
id = 'STARS'
rpc_addr = 'http://stars1:26657'
grpc_addr = 'http://stars1:9090'
event_source = { mode = 'push', url = 'ws://stars1:26657/websocket', batch_delay = '500ms' }
rpc_timeout = '10s'
account_prefix = 'stars'
key_name = 'rly5'
store_prefix = 'ibc'
default_gas = 100000
max_gas = 3000000
gas_price = { price = 0.000, denom = 'ustars' }
gas_multiplier = 1.3
clock_drift = '10s'
max_block_time = '10s'
address_type = { derivation = 'cosmos' }
trusting_period = '119s'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'stride-dockernet'