[global]
log_level = 'debug'

[mode]
[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = true

[mode.channels]
enabled = true

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true

[rest]
enabled = false
host = '0.0.0.0'
port = 3000

[telemetry]
enabled = false
host = '127.0.0.1'
port = 3001

[[chains]]
id = 'STRIDE'
rpc_addr = 'http://stride1:26657'
grpc_addr = 'http://stride1:9090'
event_source = { mode = 'push', url = 'ws://stride1:26657/websocket', batch_delay = '500ms' }
rpc_timeout = '10s'
account_prefix = 'stride'
key_name = 'rly1'
store_prefix = 'ibc'
gas_price = { price = 0.000, denom = 'ustrd' }
gas_multiplier = 1.3
clock_drift = '10s'
max_block_time = '10s'
address_type = { derivation = 'cosmos' }
trusting_period = '119s'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'stride-dockernet'

[[chains]]
id = 'CELESTIA'
rpc_addr = 'http://celestia1:26657'
grpc_addr = 'http://celestia1:9090'
event_source = { mode = 'push', url = 'ws://celestia1:26657/websocket', batch_delay = '500ms' }
rpc_timeout = '10s'
account_prefix = 'celestia'
key_name = 'rly11'
store_prefix = 'ibc'
gas_price = { price = 0.01, denom = 'utia' }
clock_drift = '10s'
max_block_time = '10s'
address_type = { derivation = 'cosmos' }
default_gas = 100000
max_gas = 400000
gas_multiplier = 1.5
max_msg_num = 30
max_tx_size = 180000
max_grpc_decoding_size = 33554432
ccv_consumer_chain = false
sequential_batch_tx = false
compat_mode = '0.34'
trusting_period = '119s'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'stride-dockernet'
