global:
  api-listen-addr: :5183
  timeout: 10s
  memo: ""
  light-cache-size: 20
chains:
  dydx:
    type: cosmos
    value:
      key: dydx
      chain-id: DYDX
      rpc-addr: http://dydx1:26657
      account-prefix: dydx
      keyring-backend: test
      gas-adjustment: 1.3
      gas-prices: 0.02udydx
      coin-type: 118
      debug: false
      timeout: 20s
      output-format: json
      sign-mode: direct
  noble:
    type: cosmos
    value:
      key: noble
      chain-id: NOBLE
      rpc-addr: http://noble1:26657
      account-prefix: noble
      keyring-backend: test
      gas-adjustment: 1.3
      gas-prices: 0.00utoken
      coin-type: 118
      debug: false
      timeout: 20s
      output-format: json
      sign-mode: direct
  osmo:
    type: cosmos
    value:
      key: osmo
      chain-id: OSMO
      rpc-addr: http://osmo1:26657
      account-prefix: osmo
      keyring-backend: test
      gas-adjustment: 1.3
      gas-prices: 0.00uosmo
      coin-type: 118
      debug: false
      timeout: 20s
      output-format: json
      sign-mode: direct
paths:
  dydx-noble:
    src:
      chain-id: DYDX
    dst:
      chain-id: NOBLE
    src-channel-filter:
      rule: ""
      channel-list: []
  noble-osmo:
    src:
      chain-id: NOBLE
    dst:
      chain-id: OSMO
    src-channel-filter:
      rule: ""
      channel-list: []
  osmo-dydx:
    src:
      chain-id: OSMO
    dst:
      chain-id: DYDX
    src-channel-filter:
      rule: ""
      channel-list: []
