apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: gcr.io/stride-nodes/integration-tests/api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              protocol: TCP
          resources:
            limits:
              cpu: "100m"
              memory: "100M"
            requests:
              cpu: "50m"
              memory: "50M"
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: integration
spec:
  selector:
    app: api
  ports:
    - port: 8000
      protocol: TCP
