apiVersion: apps/v1
kind: Deployment
metadata:
  name: hermes-stride-cosmoshub
  namespace: integration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hermes-stride-cosmoshub
  template:
    metadata:
      labels:
        app: hermes-stride-cosmoshub
    spec:
      containers:
        - name: hermes-stride-cosmoshub
          image: gcr.io/stride-nodes/integration-tests/hermes:v1.9.0
          imagePullPolicy: Always
          env:
            - name: CHAIN_NAME_A
              value: stride
            - name: CHAIN_NAME_B
              value: cosmoshub
            - name: CHAIN_A_MNEMONIC_INDEX
              value: "0"
            - name: CHAIN_B_MNEMONIC_INDEX
              value: "1"
          resources:
            limits:
              cpu: "200m"
              memory: "1000M"
            requests:
              cpu: "200m"
              memory: "1000M"
          volumeMounts:
            - name: configs
              mountPath: /home/hermes/configs
            - name: scripts
              mountPath: /home/hermes/scripts
      volumes:
        - name: configs
          configMap:
            name: configs
        - name: scripts
          configMap:
            name: scripts