on:
  workflow_dispatch:

jobs:
  build-dep-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dep-name:
          - gaia
          - hermes
          - icq
          - stride
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v0.6.0
        with:
          version: "389.0.0"
          service_account_key: ${{ secrets.GCP_KEY }}
          project_id: ${{ secrets.GCP_NODES_PROJECT }}
          export_default_credentials: true

      - name: GCloud Configure Docker
        run: |
          gcloud auth configure-docker

      - name: Construct Image
        shell: bash
        run: |
          hub_tag=stridelabs/nodes-base-images:${{ matrix.dep-name }}
          gcr_tag=gcr.io/stride-nodes/base-images/${{ matrix.dep-name }}:latest

          docker build -t $hub_tag -f scripts/testnet/dockerfiles/base/Dockerfile.${{ matrix.dep-name }} .
          docker push $hub_tag
          docker tag $hub_tag $gcr_tag
          docker push $gcr_tag
