name: Compile Stride

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# This workflow makes x86_64 binaries for mac, windows, and linux.
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64]
        targetos: [darwin, linux]
        include:
          - targetos: darwin
            arch: arm64
    name: stride ${{ matrix.arch }} for ${{ matrix.targetos }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
        env:
          GOOS: ${{ matrix.targetos }}
          GOARCH: ${{ matrix.arch }}

      - name: Compile stride
        run: make build
      - uses: actions/upload-artifact@v3
        with:
          name: strided ${{ matrix.targetos }} ${{ matrix.arch }}
          path: build/strided
