on:
  push:
    branches:
      - launch-net-actions

jobs:
  build-droplet-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v0.6.0
        with:
          version: "389.0.0"
          service_account_key: ${{ secrets.GCP_KEY }}
          project_id: ${{ secrets.GCP_NODES_PROJECT }}
          export_default_credentials: true

      - name: GCloud Configure Docker
        run: |
          gcloud auth configure-docker

      - name: Create Stride Base Image
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}"
          file: "Dockerfile.stride"
          load: true
          platforms: linux/amd64
          tags: stridezone:stride

      - name: Initialize Stride State
        shell: bash
        run: ./scripts/testnet/setup_testnet_state.sh

      # - name: Construct Test Images
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: "{{defaultContext}}"
      #     file: "scripts/testnet/dockerfiles/Dockerfile.node1"
      #     push: true
      #     platforms: linux/amd64
      #     tags: |
      #       stridelabs/internal:test-droplet-sp
      #       gcr.io/stride-nodes/testnet:test-droplet-sp
      # -
      #   name: Construct Node1 Images
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: "{{defaultContext}}"
      #     file: "scripts/testnet/dockerfiles/Dockerfile.node1"
      #     push: true
      #     platforms: linux/amd64
      #     tags: |
      #       stridelabs/internal:droplet_node1
      #       gcr.io/stride-nodes/testnet:droplet_node1
      # -
      #   name: Construct Node2 Images
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: "{{defaultContext}}"
      #     file: "scripts/testnet/dockerfiles/Dockerfile.node2"
      #     push: true
      #     platforms: linux/amd64
      #     tags: |
      #       stridelabs/internal:droplet_node2
      #       gcr.io/stride-nodes/testnet:droplet_node2
      # -
      #   name: Construct Node3 Images
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: "{{defaultContext}}"
      #     file: "scripts/testnet/dockerfiles/Dockerfile.node3"
      #     push: true
      #     platforms: linux/amd64
      #     tags: |
      #       stridelabs/internal:droplet_node3
      #       gcr.io/stride-nodes/testnet:droplet_node3
      # -
      #   name: Construct Seed Images
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: "{{defaultContext}}"
      #     file: "scripts/testnet/dockerfiles/Dockerfile.seed"
      #     push: true
      #     platforms: linux/amd64
      #     tags: |
      #       stridelabs/internal:droplet_seed
      #       gcr.io/stride-nodes/testnet:droplet_seed
      # -
      #   name: Publish to GCP
      #   run: |
      #     docker push gcr.io/stride-nodes/testnet:droplet_node1
