
on:
  push:
    branches:
      - launch-net

jobs:
  build-droplet-docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push to docker
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}"
          file: "scripts/testnet/dockerfiles/Dockerfile.node1"
          push: true
          platforms: linux/amd64
          tags: stridelabs/internal:droplet_node1
      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v0.6.0
        with:
          version: '389.0.0'
          service_account_key: ${{ secrets.GCP_KEY }} 
          project_id: ${{ secrets.GCP_NODES_PROJECT }} 
          export_default_credentials: true
      - 
        name: Publish to GCP
        run: |
          gcloud auth configure-docker
          docker tag stridelabs/internal:droplet_node1 gcr.io/stride-nodes/testnet:droplet_node1
          docker push gcr.io/stride-nodes/testnet:droplet_node1
