on:
  push:
    branches:
      - launch-net-actions

env:
  deployment_name: testnet
  network_name: stride
  num_nodes: 3

jobs:
  get-node-names:
    runs-on: ubuntu-latest
    steps:
      - id: set-output
        run: |
          node-names="[\"a\", \"b\", \"c\"]"
          echo "::set-output name=node-names::${node-names}"
    outputs:
      node-names: ${{ steps.set-output.outputs.node-names }}
  build:
    needs: get-node-names
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{ fromJson(needs.get-node-names.outputs.node-names) }}
    steps:
      - run: |
          echo "${{ matrix.value }}"

  # node-names:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - id: matrix
  #       run: |
  #         node_names="["
  #         for (( i=1; i <= $num_nodes; i++ )); do
  #           node_names+=", \"${network_name}-node${i}\""
  #         done
  #         node_names+="]"
  #         echo "::set-output name=node_names::[${node_names}]"
  #   outputs:
  #     matrix: ${{ steps.matrix.outputs.node_names }}

  # initialize-state:
  #   needs: node-names
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Build Stride
  #       run: make build

  #     - name: Initialize Stride State
  #       shell: bash
  #       run: ./scripts/testnet/setup_testnet_state.sh ${deployment_name} ${network_name} ${num_nodes}

  #     - name: Persist State Files
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: state
  #         path: ./scripts/testnet/state
  #         retention-days: 1

  # build-docker-images:
  #   needs: initialize-state
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node_names:
  #         - stride-node1
  #         - stride-node2
  #         - stride-node3
  #       # node_names: ${{fromJson(needs.node_names.outputs.matrix)}}
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2

  #     - name: Restore State Files
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: state
  #         path: ./state

  #     - name: Login to DockerHub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - name: Set up gcloud Cloud SDK environment
  #       uses: google-github-actions/setup-gcloud@v0.6.0
  #       with:
  #         version: "389.0.0"
  #         service_account_key: ${{ secrets.GCP_KEY }}
  #         project_id: ${{ secrets.GCP_NODES_PROJECT }}
  #         export_default_credentials: true

  #     - name: GCloud Configure Docker
  #       run: |
  #         gcloud auth configure-docker

  #     - name: Build Stride Node Images
  #       uses: docker/build-push-action@v3
  #       with:
  #         context: .
  #         file: "scripts/testnet/dockerfiles/Dockerfile.stride"
  #         build-args: |
  #           node_name=${{ matrix.node_names }}
  #         push: true
  #         platforms: linux/amd64
  #         tags: |
  #           stridelabs/internal:${{ matrix.node_names }}
  #           gcr.io/stride-nodes/testnet:${{ matrix.node_names }}
