on:
  push:
    branches:
      - launch-net-actions

env:
  deployment_name: testnet
  chain_name: stride
  num_nodes: 2

jobs:
  node_names:
    runs-on: ubuntu-latest
    steps:
      - id: matrix
        run: |
          node_names="[\"${chain_name}-seed\""
          for (( i=1; i <= $num_nodes; i++ )); do
            node_names+=", \"${chain_name}-node${i}\""
          done
          node_names+="]"
          echo "::set-output name=node_names::[${node_names}]"
    outputs:
      matrix: ${{ steps.matrix.outputs.node_names }}

  build-node-images:
    needs: node_names
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_names: ${{fromJson(needs.node_names.outputs.matrix)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Show
        run: echo "======================${{ matrix.node_names }}================================="

      # - name: Login to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Set up gcloud Cloud SDK environment
      #   uses: google-github-actions/setup-gcloud@v0.6.0
      #   with:
      #     version: "389.0.0"
      #     service_account_key: ${{ secrets.GCP_KEY }}
      #     project_id: ${{ secrets.GCP_NODES_PROJECT }}
      #     export_default_credentials: true

      # - name: GCloud Configure Docker
      #   run: |
      #     gcloud auth configure-docker

      # - name: Build Stride
      #   run: make build

      # - name: Initialize Stride State
      #   shell: bash
      #   run: ./scripts/testnet/setup_testnet_state.sh ${deployment_name} ${chain_name} ${num_nodes}

      # - name: Build Stride Seed Node Image
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     file: "scripts/testnet/dockerfiles/Dockerfile.stride"
      #     build-args: |
      #       deployment_name=testnet
      #       node_name=stride-seed
      #     push: true
      #     platforms: linux/amd64
      #     tags: |
      #       stridelabs/internal:stride-seed
      #       gcr.io/stride-nodes/testnet:stride-seed

      # - name: Build Stride Node Images
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     file: "scripts/testnet/dockerfiles/Dockerfile.stride"
      #     build-args: |
      #       deployment_name=testnet
      #       node_name=${{ matrix.node_names }}
      #     push: true
      #     platforms: linux/amd64
      #     tags: |
      #       stridelabs/internal:stride-node1
      #       gcr.io/stride-nodes/testnet:stride-node1
      # -
      #   name: Construct Node1 Images
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: "{{defaultContext}}"
      #     file: "scripts/testnet/dockerfiles/Dockerfile.node1"
      #     push: true
      #     platforms: linux/amd64
      #     tags: |
      #       stridelabs/internal:droplet_node1
      #       gcr.io/stride-nodes/testnet:droplet_node1
      # -
      #   name: Construct Node2 Images
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: "{{defaultContext}}"
      #     file: "scripts/testnet/dockerfiles/Dockerfile.node2"
      #     push: true
      #     platforms: linux/amd64
      #     tags: |
      #       stridelabs/internal:droplet_node2
      #       gcr.io/stride-nodes/testnet:droplet_node2
      # -
      #   name: Construct Node3 Images
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: "{{defaultContext}}"
      #     file: "scripts/testnet/dockerfiles/Dockerfile.node3"
      #     push: true
      #     platforms: linux/amd64
      #     tags: |
      #       stridelabs/internal:droplet_node3
      #       gcr.io/stride-nodes/testnet:droplet_node3
      # -
      #   name: Construct Seed Images
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: "{{defaultContext}}"
      #     file: "scripts/testnet/dockerfiles/Dockerfile.seed"
      #     push: true
      #     platforms: linux/amd64
      #     tags: |
      #       stridelabs/internal:droplet_seed
      #       gcr.io/stride-nodes/testnet:droplet_seed
      # -
      #   name: Publish to GCP
      #   run: |
      #     docker push gcr.io/stride-nodes/testnet:droplet_node1
