name: Labeler
on:
  push:
    branches: [ "sttia" ]
  pull_request:
    branches: [ "sttia" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4.0.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
