name: Labeler
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4.0.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        
  
