name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  golangci:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.3

      - name: golangci-lint
      - uses: golangci/golangci-lint-action@v3.2.0
        with:
            version: v1.46.2
